/* ============================================================
   stackview — the whole of the user-visible text, in both languages.

   `en` is the app exactly as it has always read. `ar` is the same app
   written in Arabic rather than translated word by word: Modern Standard
   Arabic as a Gulf engineer would write it, with the vocabulary that gets
   typed in English left in English — AWS, EC2, Kubernetes, SLO, MFA,
   region codes, hostnames, IDs, emails.

   The two halves have the same shape. A key missing from `ar` falls back
   to `en` (see lib/i18n.js), so a gap degrades to English rather than to
   a raw key.

   Values are strings or functions. A function receives the interpolation
   bag: `t('alerts.openN', { n: 4 })`.
   ============================================================ */

/* ---------- Arabic counted nouns ----------
   Arabic counts in four shapes, not two. `arN(3, {...})` picks the right
   one: one (خادم واحد), two (خادمان), few for 3–10 (٣ خوادم), many for
   11 and up (١٥ خادماً). `zero` is optional and falls back to `many`.  */
export function arN(n, f) {
  const m = Math.abs(Number(n) || 0) % 100;
  if (n === 0 && f.zero !== undefined) return f.zero;
  if (n === 1) return f.one;
  if (n === 2) return f.two;
  if (m >= 3 && m <= 10) return f.few;
  return f.many;
}

/* English plural, matching the shape the app already used. */
export const enN = (n, one, many) => `${n} ${n === 1 ? one : many || `${one}s`}`;

const EN = {
  /* ---------- shell ---------- */
  app: {
    name: 'stackview',
    tag: 'IT visibility',
    tenant: 'Tenant',
    docTitle: ({ title }) => `${title} · stackview`,
  },

  routes: {
    overview: { title: 'Overview', sub: 'Estate at a glance' },
    alerts: { title: 'Alerts', sub: 'Open and acknowledged' },
    uptime: { title: 'Uptime', sub: 'Last 30 days' },
    resources: { title: 'Resources', sub: 'Inventory' },
    cost: { title: 'Cost', sub: 'Spend and waste' },
    access: { title: 'Access', sub: 'Users and roles' },
    reports: { title: 'Reports', sub: 'Monthly review' },
  },
  navgroups: { Monitor: 'Monitor', Estate: 'Estate', Governance: 'Governance' },

  chrome: {
    primaryNav: 'Primary',
    openNav: 'Open navigation',
    closePanel: 'Close panel',
    railCollapse: 'Collapse sidebar',
    railExpand: 'Expand sidebar',
    tone: 'Sidebar colour',
    devicePreview: 'Device preview',
    phonePreview: 'Preview at phone size',
    desktopPreview: 'Back to desktop size',
    backToDesktop: 'Back to desktop',
    phoneFrameTitle: 'Stackview running in a 390 by 844 phone viewport',
    phoneSize: 'phone preview · 390 × 844',
    themeToLight: 'Switch to light mode',
    themeToDark: 'Switch to dark mode',
    navOpenSuffix: ({ n }) => `(${n} open)`,
    aboutDemo: 'About this demo',
    aboutPillTitle: 'Every figure, resource, account and alert here is invented sample data and nothing leaves your browser. Open for the detail.',
    aboutPillLong: 'About this ',
    aboutPillShort: 'demo',
    reset: 'Reset demo data',
    resetBody: 'This clears every change you made in this demo — acknowledged alerts, cleanup plans, offboarding progress and generated reports — and rebuilds the sample estate.',
    resetOk: 'Reset',
    resetDone: 'Demo data reset',
    site: 'nasvih.in',
    siteLabel: 'nasvih.in — opens in a new tab',
    github: 'GitHub',
    githubLabel: 'GitHub — opens the source repository in a new tab',
    sourceOnGithub: 'Source on GitHub',
    sourceOnGithubLabel: 'Source on GitHub — opens in a new tab',
    viewErrorTitle: 'This screen could not be drawn',
    viewErrorBody: 'Reset the demo data from the sidebar to rebuild the sample estate.',
  },

  /* ---------- shared UI runtime ---------- */
  ui: {
    confirmTitle: 'Confirm',
    confirmOk: 'Confirm',
    cancel: 'Cancel',
    close: 'Close',
    install: 'Install app',
    installTitle: ({ app }) => `Install ${app} on this device`,
    installed: ({ app }) => `${app} installed. It opens in its own window from now on.`,
    installDismissed: 'Install dismissed — the button stays here if you change your mind.',
    installIOS: 'On iPhone and iPad: tap Share, then "Add to Home Screen".',
    installOther: 'Use your browser menu and choose "Install app" or "Add to Home screen".',
  },

  time: {
    now: 'just now',
    mins: ({ n }) => `${n}m ago`,
    hours: ({ n }) => `${n}h ago`,
    days: ({ n }) => `${n}d ago`,
    today: 'today',
    daysAgoShort: ({ n }) => `${n}d ago`,
  },

  /* ---------- vocabulary of the estate ---------- */
  states: {
    running: 'running', available: 'available', degraded: 'degraded',
    stopped: 'stopped', unattached: 'unattached', unassociated: 'unassociated',
  },
  envs: { prod: 'prod', staging: 'staging', dev: 'dev', shared: 'shared' },
  sev: { critical: 'critical', high: 'high', warning: 'warning', info: 'info' },
  alertStatus: { open: 'open', acked: 'acknowledged', muted: 'muted', resolved: 'resolved' },
  roles: {
    Admin: 'Admin', 'Power user': 'Power user', Developer: 'Developer',
    'Read only': 'Read only', Billing: 'Billing',
  },
  providers: { aws: 'AWS', azure: 'Azure', onprem: 'On-prem' },
  directories: { 'AWS IAM': 'AWS IAM', 'Entra ID': 'Entra ID', 'on-prem AD': 'on-prem AD' },
  teams: {
    Platform: 'Platform', Payments: 'Payments', Data: 'Data',
    'Retail Apps': 'Retail Apps', 'Facilities IT': 'Facilities IT',
  },
  serviceGroups: {
    Compute: 'Compute', Kubernetes: 'Kubernetes', Databases: 'Databases',
    Storage: 'Storage', Network: 'Network', 'Backup & DR': 'Backup & DR',
    'On-prem & DC': 'On-prem & DC', Integration: 'Integration',
    'Security & identity': 'Security & identity', Observability: 'Observability',
    Other: 'Other',
  },
  sources: { 'Cost guard': 'Cost guard' },
  months: {
    Jan: 'Jan', Feb: 'Feb', Mar: 'Mar', Apr: 'Apr', May: 'May', Jun: 'Jun',
    Jul: 'Jul', Aug: 'Aug', Sep: 'Sep', Oct: 'Oct', Nov: 'Nov', Dec: 'Dec',
  },
  tiers: { 'Tier 1': 'Tier 1', 'Tier 2': 'Tier 2', 'Tier 3': 'Tier 3' },
  uptimeServices: {
    'Checkout API': 'Checkout API',
    'Orders API': 'Orders API',
    Storefront: 'Storefront',
    'Payments webhook': 'Payments webhook',
    'Warehouse sync': 'Warehouse sync',
    'Admin console': 'Admin console',
    'Facilities VPN': 'Facilities VPN',
    'Mail relay': 'Mail relay',
  },
  offboard: [
    'Disable the directory account and revoke active sessions',
    'Deactivate and delete cloud access keys',
    'Remove from VPN and bastion allow lists',
    'Transfer ownership of resources tagged to the user',
    'Remove from source control and pipeline groups',
    'Collect the laptop and any hardware token',
    'Archive the mailbox and set a forwarding rule',
  ],

  /* ---------- the activity feed and the alert timelines ----------
     Written as keys rather than as sentences so the feed comes back in
     whichever language the reader is in, not the one they were in when
     they pressed the button. */
  activity: {
    seedVolumes: ({ n }) => `Cost guard flagged ${n} unattached volumes`,
    seedScaled: 'eks-prod-ng-general scaled from 3 to 4 nodes',
    seedReview: ({ n }) => `Access review opened for ${n} stale accounts`,
    alertsAcked: ({ n }) => `${n} alerts acknowledged`,
    alertAcked: ({ id }) => `${id} acknowledged`,
    alertMuted: ({ id }) => `${id} muted`,
    alertUnmuted: ({ id }) => `${id} unmuted`,
    alertResolved: ({ id }) => `${id} resolved`,
    planAdded: ({ name }) => `${name} added to the cleanup plan`,
    planRemoved: ({ name }) => `${name} removed from the cleanup plan`,
    reassigned: ({ name, to }) => `${name} reassigned to ${to}`,
    stopped: ({ name }) => `${name} stopped`,
    started: ({ name }) => `${name} started`,
    deleted: ({ name, money }) => `${name} deleted — ${money}/mo released`,
    offboardStarted: ({ name }) => `Offboarding started for ${name}`,
    offboarded: ({ name }) => `${name} offboarded and disabled`,
    roleChanged: ({ name, from, to }) => `${name} role changed from ${from} to ${to}`,
    mfaOn: ({ name }) => `MFA enforced on ${name}`,
    mfaOff: ({ name }) => `MFA removed from ${name}`,
    keyRotated: ({ name }) => `Access key rotated for ${name}`,
    maintOn: ({ name, date }) => `${name} ${date} reclassified as planned maintenance`,
    maintOff: ({ name, date }) => `${name} ${date} returned to unplanned`,
    reviewGenerated: ({ id, month }) => `Monthly review ${id} generated for ${month}`,
    aiAcked: ({ n }) => `${n} alert${n === 1 ? '' : 's'} acknowledged from the assistant`,
    aiMuted: ({ n }) => `${n} alert${n === 1 ? '' : 's'} muted from the assistant`,
    aiUnmuted: ({ n }) => `${n} alert${n === 1 ? '' : 's'} unmuted from the assistant`,
    aiPlan: ({ n }) => `${n} finding${n === 1 ? '' : 's'} added to the cleanup plan from the assistant`,
    aiPlanOne: ({ name }) => `${name} added to the cleanup plan from the assistant`,
    aiStopped: ({ name }) => `${name} stopped from the assistant`,
    aiStoppedProd: ({ name }) => `${name} stopped from the assistant (production)`,
    aiStarted: ({ name }) => `${name} started from the assistant`,
    aiReassigned: ({ name, from, to }) => `${name} reassigned from ${from} to ${to} by the assistant`,
    aiOffboard: ({ name }) => `Offboarding started for ${name} from the assistant`,
    aiMfa: ({ n }) => `MFA enforced on ${n} account${n === 1 ? '' : 's'} from the assistant`,
    aiTagged: ({ n }) => `${n} resource${n === 1 ? '' : 's'} tagged from the assistant`,
  },
  timeline: {
    opened: 'Alert opened',
    acked: 'Acknowledged',
    ackedBulk: 'Acknowledged in bulk',
    muted: 'Muted for 24 hours',
    unmuted: 'Unmuted',
    resolved: 'Marked resolved',
    aiAcked: 'Acknowledged from Stackview Insight',
    aiMuted: 'Muted for 24 hours from Stackview Insight',
    aiUnmuted: 'Unmuted from Stackview Insight',
  },

  /* ---------- about this demo ---------- */
  about: {
    title: 'About Stackview',
    ok: 'Got it',
    lead: 'The estate on these screens — Northline Group, its resources, people and bills — is invented sample data.',
    whatTitle: 'What this is',
    whatText: 'Stackview is one picture of what a business runs and what it pays for. It puts every resource — across cloud providers and the on-prem racks — in a single inventory, then reads cost by service, by environment and by team on top of it. Access and MFA status, open alerts and 30-day uptime sit on the same estate, so the answer to "what do we run, what does it cost, who can get into it" is one screen rather than three consoles.',
    helpTitle: 'Where it helps a business',
    help: [
      ['One inventory', 'nobody opens three provider consoles to answer "what do we run". Cloud and on-prem are in the same table, with the same filters.'],
      ['Waste is found before the bill', 'idle and forgotten resources are listed with a reason and a monthly figure, instead of being noticed at billing time.'],
      ['Every resource has an owner', 'ownership is attached to the resource, so there is a named person to ask before anything is switched off.'],
      ['Access review is already written', 'stale accounts, admin without MFA and old keys are listed continuously, so the review stops being an annual scramble.'],
      ['Alerts leave a trail', 'acknowledgements and mutes are recorded against the alert, so an incident can be reconstructed after the fact.'],
    ],
    realTitle: 'How it would work for real',
    realText: 'The same interface, reading from the provider APIs and the identity directory instead of sample data, with the inventory, the cost lines and the access findings refreshed on a schedule. What you are looking at here is the interface and the workflow — no account is connected and nothing is being polled.',
    demoTitle: 'How this demo works',
    demo: [
      ['You can actually use it', 'acknowledge and mute alerts, stop resources and reassign owners, work the idle and waste list, run the access review and the offboarding checklist, generate a monthly review. Nothing on these screens is read only.'],
      ['Your data stays on your machine', 'everything you change is saved in this browser\'s local storage. There is no account and no backend. "Reset demo data" clears it, and it does not sync between browsers or devices.'],
      ['The assistant is simulated', 'Stackview Insight answers by matching your question against this app\'s own demo data. It is a demonstration of the interaction, not a connected model, and no request leaves your browser.'],
    ],
    askTitle: 'What you can ask the assistant to do',
    askLead: 'Stackview Insight does not only report. Type one of these and it names exactly what it is about to touch, then applies it when you press the button — never before.',
    itDoes: ({ does }) => `It ${does}`,
    landsOn: ({ screen }) => `Lands on ${screen}`,
    sourceTitle: 'The source',
    sourceNote: 'The source is published so it can be read, run and evaluated. It is not open source — copying, modifying, redistributing, deploying it or using it as training data needs written permission. See the LICENSE file in the repository.',
  },

  /* ---------- notifications ---------- */
  notif: {
    title: 'Notifications',
    panelLabel: 'Notifications',
    unreadCount: ({ n, total }) => `${n} unread of ${total}`,
    nothingOpen: 'nothing open',
    markAll: 'Mark all read',
    markRead: 'Mark as read',
    markReadOne: ({ title }) => `Mark "${title}" as read`,
    closeLabel: 'Close notifications',
    bellUnread: ({ n }) => `Notifications, ${n} unread`,
    bellClear: 'Notifications, nothing unread',
    emptyTitle: 'Nothing needs you',
    emptyBody: 'No critical alert is open, the month is tracking close to last month, every elevated account has a second factor and no key is past a year. This list is built from the estate, so it fills up again as things change.',
    kindCritical: 'Critical alert',
    kindBudget: 'Budget drift',
    kindMfa: 'No MFA',
    kindKey: 'Old key',
    kindIdle: 'Idle for weeks',
    budgetTitle: ({ money, dir, month }) => `Month end is tracking ${money} ${dir} ${month}`,
    budgetAbove: 'above',
    budgetBelow: 'below',
    budgetBody: ({ projected, prev, pct, dir }) => `${projected} projected against ${prev} last month, ${pct} ${dir}.`,
    budgetUp: 'up',
    budgetDown: 'down',
    mfaTitle: ({ name, role }) => `${name} holds ${role} with no second factor`,
    mfaBody: ({ directory, team, ago }) => `${directory} · ${team} · last signed in ${ago}`,
    keyTitle: ({ name, days }) => `${name} has an access key ${days} days old`,
    keyBody: 'The policy is 90 days. Rotate it from the account drawer.',
    idleTitle: ({ name, money }) => `${name} is idle at ${money} a month`,
  },

  /* ---------- overview ---------- */
  overview: {
    title: ({ org }) => `${org} estate`,
    lead: ({ n }) => `${n} resources across AWS, Azure and two data centres. Costs are shown at the current month run rate, converted to SAR for the Jeddah entity where it matters.`,
    openCost: 'Open cost',
    openAlerts: ({ n }) => `${n} open alerts`,
    statSpend: 'Spend this month',
    statSpendDelta: ({ projected, sar }) => `${projected} projected at month end · ${sar}`,
    statResources: 'Resources',
    statResourcesDelta: ({ running, idle }) => `${running} running · ${idle} idle or detached`,
    statAlerts: 'Open alerts',
    statAlertsDelta: ({ crit, ago }) => `${crit} critical, oldest ${ago}`,
    statAlertsClear: 'No critical alerts open',
    statUptime: 'Uptime 30 days',
    statUptimeDelta: ({ n }) => `${n} tracked services`,
    monthlySpend: 'Monthly spend',
    vsPrev: ({ sign, pct, month }) => `${sign}${pct}% vs ${month}`,
    spendNote: ({ prev, prevTotal, cur, diff, dir }) => `${prev} closed at ${prevTotal}. ${cur} is tracking ${diff} ${dir}.`,
    higher: 'higher',
    lower: 'lower',
    byEnv: 'By environment',
    nonProd: ({ pct }) => `Non-production is ${pct} of the bill.`,
    provSub: ({ n, regions }) => `${n} resources · ${regions} regions`,
    wasteTitle: 'Idle and waste',
    openFinder: 'Open finder',
    wasteBannerLead: ({ money }) => `${money} a month`,
    wasteBannerMid: ' is sitting in ',
    wasteBannerTail: ({ n, pct }) => ` resources that are idle, detached or oversized. That is ${pct} of the run rate.`,
    thResource: 'Resource',
    thWhy: 'Why',
    thSaving: 'Saving',
    latestAlerts: 'Latest alerts',
    allAlerts: 'All alerts',
    nothingOpen: 'Nothing open',
    nothingOpenBody: 'Every alert has been acknowledged or muted.',
    hygiene: 'Access hygiene',
    review: 'Review',
    hygieneNoMfa: 'Admins without MFA',
    hygieneStale: 'Stale accounts',
    hygieneKeys: 'Keys older than a year',
    hygieneUntagged: 'Untagged resources',
    hygieneNote: ({ names }) => `${names} hold elevated roles with no second factor.`,
    recentActivity: 'Recent activity',
  },

  /* ---------- alerts ---------- */
  alerts: {
    lead: 'Everything firing across CloudWatch, Azure Monitor, Alertmanager, Zabbix, Nagios and the backup software, in one queue. Acknowledging an alert records who picked it up.',
    export: 'Export',
    exported: 'Alerts exported',
    csv: ['Id', 'Severity', 'Title', 'Resource', 'Service', 'Source', 'Opened', 'Status', 'Acknowledged by'],
    ackAll: 'Acknowledge all open',
    nothingLeftOpen: 'Nothing left open',
    ackAllBody: ({ n, me }) => `Acknowledge ${n} open alerts as ${me}. They stay in the queue until they are resolved.`,
    ackAllTitle: 'Acknowledge all',
    ackAllOk: 'Acknowledge',
    ackedToast: ({ n }) => `${n} alerts acknowledged`,
    statOpen: 'Open',
    statOpenOldest: ({ ago }) => `oldest ${ago}`,
    statOpenClear: 'queue clear',
    statCritical: 'Critical',
    statCriticalSub: 'page the on call engineer',
    statAcked: 'Acknowledged',
    statAckedSub: 'picked up, not fixed',
    statMuted: 'Muted',
    statMutedSub: 'hidden from the queue',
    filterSeverity: 'Severity',
    filterStatus: 'Status',
    all: 'All',
    any: 'Any',
    /* the status chips read as the queue does, except this one, which the
       filter bar has always shown capitalised */
    chipAcked: 'Acknowledged',
    emptyTitle: 'Nothing here',
    emptyBody: 'No alert matches this filter. Try "Any" status.',
    meta: ({ source, resource, date, time, ago }) => `${source} · ${resource} · opened ${date} ${time} (${ago})`,
    ackedBy: ({ who }) => ` · acknowledged by ${who}`,
    ack: 'Acknowledge',
    mute24: 'Mute 24h',
    unmute: 'Unmute',
    resolve: 'Resolve',
    timeline: 'Timeline',
    toastAcked: 'Alert acknowledged',
    toastMuted: 'Alert muted',
    toastUnmuted: 'Alert unmuted',
    toastResolved: 'Alert resolved',
    kvId: 'Alert id',
    kvService: 'Service',
    kvResource: 'Resource',
    kvOpened: 'Opened',
    kvAge: 'Age',
    kvAckedBy: 'Acknowledged by',
    nobodyYet: 'nobody yet',
    notePlaceholder: 'Add a note to the timeline',
    noteLabel: 'Timeline note',
    noteEmpty: 'Type a note first',
    noteAdded: 'Note added',
    add: 'Add',
  },

  /* ---------- cost ---------- */
  cost: {
    lead: 'Run rate for the current month, split three ways. On-prem hardware is amortised so a data centre host can be compared with an instance.',
    exportBreakdown: 'Export breakdown',
    exportedBreakdown: 'Breakdown exported',
    csvBreakdown: ['Month', 'Service', 'USD'],
    tileRunRate: 'Run rate',
    tileRunRateSub: ({ sar }) => `${sar} at 3.75`,
    tileMtd: 'Month to date',
    tileMtdSub: ({ day, days }) => `day ${day} of ${days}`,
    tileMover: 'Biggest mover',
    tileMoverSub: ({ sign, money, month }) => `${sign}${money} vs ${month}`,
    tileWaste: 'Idle and waste',
    tileWasteSub: ({ n }) => `${n} findings open`,
    banner: 'These figures are invented sample data, not a real bill. Nothing is read from a cloud billing account and your cleanup plan is saved in this browser only.',
    tabService: 'By service',
    tabEnv: 'By environment',
    tabTeam: 'By team',
    tabWaste: 'Idle and waste',
    trend: 'Seven month trend',
    trendRange: ({ from, to }) => `${from} to ${to}`,
    thGroup: 'Service group',
    thShare: 'Share',
    thChange: 'Change',
    thTotal: 'Total',
    jumpLead: ({ label, money }) => `${label} is the biggest jump this month, up ${money}. `,
    jumpK8s: 'eks-prod-ng-general went from three to four m6i.2xlarge nodes on the 6th and the extra node has stayed up since.',
    jumpOther: 'Check the resources in this group for a size change or a new deployment.',
    runRateBy: ({ label }) => `Run rate by ${label}`,
    groupEnv: 'Environment',
    groupTeam: 'Team',
    groupEnvLower: 'environment',
    groupTeamLower: 'team',
    thResources: 'Resources',
    thMonthly: 'Monthly',
    thWaste: 'Waste',
    thProviders: 'Providers',
    savingTotal: 'Total potential saving',
    savingSub: ({ n, pct, sar }) => `${n} findings · ${pct} of the run rate · ${sar} a month`,
    inPlan: 'In the cleanup plan',
    inPlanSub: ({ n, total }) => `${n} of ${total} picked up`,
    nothingFlagged: 'Nothing flagged',
    nothingFlaggedBody: 'Every finding has been dismissed or the resource has gone. Reset the demo data to bring them back.',
    doThis: 'Do this: ',
    addToPlan: 'Add to cleanup plan',
    inPlanBtn: 'In cleanup plan',
    removedFromPlan: 'Removed from plan',
    addedToPlan: 'Added to cleanup plan',
    dismiss: 'Dismiss',
    dismissed: 'Finding dismissed',
    openInInventory: 'Open in inventory',
    dismissedNote: ({ n, names }) => `${n} finding${n > 1 ? 's' : ''} dismissed: ${names}`,
    restore: 'Restore',
    restored: 'Dismissed findings restored',
    planTitle: 'Cleanup plan',
    exportPlan: 'Export plan',
    exportedPlan: 'Cleanup plan exported',
    csvPlan: ['Resource', 'Provider', 'Environment', 'Owner', 'Monthly saving USD', 'Reason', 'Action'],
    csvTotal: 'Total',
    planNote: ({ month, year }) => `Hand this list to the owners. Done in full it takes ${month} a month off the bill, ${year} over a year.`,
    perMonth: ({ money }) => `${money}/mo`,
  },

  /* ---------- resources ---------- */
  resources: {
    lead: 'Everything the group runs, in one list. Costs are the current month run rate for that resource, including on-prem hardware amortised over its refresh cycle.',
    exportCsv: 'Export CSV',
    exported: 'Inventory exported',
    csv: ['Name', 'Provider', 'Type', 'Size', 'Environment', 'Region', 'State', 'Monthly USD', 'Owner', 'Team', 'Tagged'],
    yes: 'yes',
    no: 'no',
    banner: 'This estate is invented sample data. No cloud account or data centre is connected, and any change you make here is saved in this browser only.',
    searchPlaceholder: 'Search name, type, region, owner, tag',
    searchLabel: 'Search resources',
    all: 'All',
    filterProvider: 'Provider',
    filterEnv: 'Environment',
    filterState: 'State',
    filterTeam: 'Team',
    count: ({ n, total, money }) => `${n} of ${total} · ${money}/mo`,
    emptyTitle: 'No resources match',
    emptyBody: 'Clear a filter or search for something else.',
    thResource: 'Resource',
    thType: 'Type',
    thEnv: 'Environment',
    thRegion: 'Region',
    thState: 'State',
    thMonthly: 'Monthly',
    thOwner: 'Owner',
    thTags: 'Tags',
    sortBy: ({ label }) => `Sort by ${label}`,
    openRow: ({ name }) => `Open ${name}`,
    tagCount: ({ n }) => `${n} tags`,
    untagged: 'untagged',
    kvType: 'Type',
    kvRegion: 'Region',
    kvCost: 'Monthly cost',
    kvGroup: 'Service group',
    kvOwner: 'Owner',
    kvTeam: 'Team',
    kvAge: 'Age',
    kvAgeVal: ({ n }) => `${n} days`,
    kvLastMetric: 'Last metric',
    kvLastMetricVal: ({ n }) => `${n}h ago`,
    utilTitle: 'Utilisation, 30 day average',
    cpu: 'CPU',
    memory: 'Memory',
    disk: 'Disk',
    netOut: 'Network out',
    tags: 'Tags',
    noTags: 'No tags. This resource will not show up in any cost allocation report.',
    tagBanner: 'Missing Owner, CostCentre and ManagedBy. The tag policy marks this as unallocated spend.',
    wasteFinding: 'Waste finding',
    suggestedAction: 'Suggested action: ',
    inPlan: 'In cleanup plan',
    addToPlan: 'Add to cleanup plan',
    addedToPlan: 'Added to cleanup plan',
    removedFromPlan: 'Removed from cleanup plan',
    dismissFinding: 'Dismiss finding',
    dismissed: 'Finding dismissed',
    noteTitle: 'Runbook note',
    notePlaceholder: 'Why this resource exists, who asked for it, when it can go…',
    saveNote: 'Save note',
    noteSaved: 'Note saved',
    actions: 'Actions',
    reassignLabel: 'Reassign owner',
    ownerField: 'Owner',
    reassign: 'Reassign',
    ownerUpdated: 'Owner updated',
    startResource: 'Start resource',
    stopResource: 'Stop resource',
    stopProdBody: ({ name }) => `${name} is a production resource. Stopping it in this demo will show it as stopped everywhere, including uptime and cost.`,
    stopProdTitle: 'Stop production resource',
    stopProdOk: 'Stop it',
    toastStopped: ({ name }) => `${name} stopped`,
    toastStarted: ({ name }) => `${name} started`,
    deleteResource: 'Delete resource',
    deleteBody: ({ name, money }) => `Remove ${name} from the inventory and stop the ${money} monthly charge.`,
    deleteTitle: 'Delete resource',
    deleteOk: 'Delete',
    toastDeleted: ({ name }) => `${name} deleted`,
  },

  /* ---------- access ---------- */
  access: {
    lead: 'Human and service accounts across AWS IAM, Entra ID and the on-prem directory. An account counts as stale after 60 days without a sign in.',
    exportReview: 'Export review',
    exported: 'Access review exported',
    csv: ['Name', 'Email', 'Team', 'Role', 'Directory', 'MFA', 'Last login', 'Days since login', 'Key age days', 'Status'],
    yes: 'yes',
    no: 'no',
    searchPlaceholder: 'Search name, email, team',
    searchLabel: 'Search accounts',
    fEveryone: 'Everyone',
    fElevated: 'Elevated',
    fNoMfa: 'No MFA',
    fStale: 'Stale',
    fService: 'Service accounts',
    fOffboarding: 'Offboarding',
    statAccounts: 'Accounts',
    statAccountsSub: ({ n }) => `${n} service accounts`,
    statMfa: 'MFA coverage',
    statMfaSub: ({ n }) => `${n} without a second factor`,
    statNoMfa: 'Admins without MFA',
    statClear: 'Clear',
    statStale: 'Stale accounts',
    statStaleSub: 'No sign in for 60 days or more',
    emptyTitle: 'No accounts match',
    emptyBody: 'Try another filter.',
    thAccount: 'Account',
    thRole: 'Role',
    thDirectory: 'Directory',
    thMfa: 'MFA',
    thLastLogin: 'Last login',
    thKey: 'Access key',
    thStatus: 'Status',
    openRow: ({ name }) => `Open ${name}`,
    svc: 'SVC',
    on: 'on',
    off: 'off',
    statusActive: 'active',
    statusStale: 'stale',
    statusService: 'service',
    statusDisabled: 'disabled',
    statusOffboarding: 'offboarding',
    mfaOn: 'MFA on',
    mfaOff: 'MFA off',
    kvEmail: 'Email',
    kvTeam: 'Team',
    kvLastLogin: 'Last login',
    kvKeyAge: 'Access key age',
    kvKeyAgeVal: ({ n }) => `${n} days`,
    noKey: 'no key',
    kvOwned: 'Owned resources',
    kvStatus: 'Status',
    noMfaBanner: 'No second factor on this account. ',
    noMfaElevated: 'It holds an elevated role, so this is the first thing to fix in the review.',
    noMfaOther: 'Enforce it before the next access review closes.',
    keyBanner: ({ n }) => `Access key is ${n} days old. The policy is 90 days.`,
    owns: 'Owns',
    offboarding: 'Offboarding',
    offboardLead: 'Starting offboarding opens the seven step checklist and marks the account for review. Nothing is deleted in this demo.',
    startOffboard: 'Start offboarding',
    offboardStarted: 'Offboarding started',
    completeOffboard: 'Complete offboarding',
    completeBody: ({ name, n }) => `Close the offboarding for ${name}. The account will show as disabled and its ${n} resources stay flagged until they are reassigned.`,
    completeTitle: 'Complete offboarding',
    completeOk: 'Complete',
    offboardComplete: 'Offboarding complete',
    cancel: 'Cancel',
    offboardCancelled: 'Offboarding cancelled',
    actions: 'Actions',
    changeRole: 'Change role',
    roleField: 'Role',
    apply: 'Apply',
    roleUpdated: 'Role updated',
    removeMfa: 'Remove MFA requirement',
    enforceMfa: 'Enforce MFA',
    mfaRemoved: 'MFA requirement removed',
    mfaEnforced: 'MFA enforced',
    rotateKey: 'Rotate access key',
    keyRotated: 'Access key rotated',
  },

  /* ---------- uptime ---------- */
  uptime: {
    lead: 'Thirty days of daily availability per service. Each block is one day; hover or focus a block for the numbers. Days marked as planned maintenance are left out of the error budget.',
    allTiers: 'All tiers',
    word: { up: 'operational', deg: 'degraded', down: 'outage', maint: 'planned maintenance' },
    legend: 'Legend',
    statFleet: 'Fleet uptime',
    statFleetSub: ({ n }) => `${n} services tracked`,
    statDown: 'Downtime 30d',
    statDownVal: ({ n }) => `${n}m`,
    statDownSub: 'excluding planned maintenance',
    statBelow: 'Below SLO',
    statBelowClear: 'every service inside target',
    statWorst: 'Worst day',
    statWorstSub: 'largest single day loss',
    svcSub: ({ tier, slo, resource }) => `${tier} · target ${slo}% · ${resource}`,
    insideTarget: 'inside target',
    belowTarget: 'below target',
    stripLabel: ({ name }) => `${name} daily status, last 30 days`,
    dayTitle: ({ date, word, mins }) => `${date} — ${word}${mins ? `, ${mins} min lost` : ''}`,
    dayLabel: ({ date, word }) => `${date} ${word}`,
    range: ({ from }) => `${from} → today`,
    badDays: ({ n, mins }) => `${n} bad day${n > 1 ? 's' : ''}, ${mins} min lost`,
    noIncidents: 'no incidents',
    budget: ({ used, total }) => `error budget ${used} used of ${total}m`,
    emptyTier: 'No services in this tier',
    kvService: 'Service',
    kvDate: 'Date',
    kvAvailability: 'Availability',
    kvMins: 'Minutes lost',
    kvBacking: 'Backing resource',
    kvTarget: 'Target',
    probeNote: ({ mins, date }) => `The probe recorded ${mins} minutes outside target on ${date}. Correlate with the alert queue for that window before you write the review note.`,
    probeClear: 'No probe failures recorded on this day.',
    classification: 'Classification',
    classificationNote: 'Planned maintenance is excluded from the error budget and from the fleet number on the overview.',
    markMaint: 'Mark as planned maintenance',
    markedMaint: 'Marked as planned maintenance',
    toastMaint: 'Marked as planned maintenance',
    toastUnplanned: 'Back to unplanned',
    alertBanner: 'Alerts raised on this service are in the alert queue. Filter by "Any" status to see resolved ones.',
    drawerTitle: ({ name, date }) => `${name} — ${date}`,
  },

  /* ---------- reports ---------- */
  reports: {
    lead: ({ month, year }) => `The monthly infrastructure review for ${month} ${year}. Generating a review freezes the current numbers so you can compare against it later; the CSV is the file you attach to the meeting invite.`,
    generate: 'Generate monthly review',
    tileRunRate: 'Run rate',
    tileVs: ({ month }) => `vs ${month}`,
    tileUptime: 'Uptime',
    tileUptimeSub: ({ n }) => `${n} services`,
    tileSaving: 'Saving available',
    tileSavingSub: ({ n }) => `${n} findings`,
    notesTitle: ({ month, year }) => `Review notes — ${month} ${year}`,
    noteSpend: 'Spend',
    noteSpendText: ({ run, diff, dir, prev, mtd, day, days, sar }) => `Run rate is ${run} a month, ${diff} ${dir} ${prev}. Month to date is ${mtd} on day ${day} of ${days}. The Jeddah entity share converts to ${sar}.`,
    above: 'above',
    below: 'below',
    noteEstate: 'Estate',
    onpremWord: 'on-prem',
    noteEstateText: ({ n, split, untagged }) => `${n} resources: ${split}. ${untagged} are missing the required tags and land in unallocated spend.`,
    noteWaste: 'Waste',
    noteWasteText: ({ n, money, planned }) => `${n} findings worth ${money} a month. ${planned} are in the cleanup plan.`,
    noteReliability: 'Reliability',
    noteReliabilityText: ({ pct, below }) => `Fleet uptime ${pct} over 30 days. ${below} service(s) below target.`,
    noteAlerts: 'Alerts',
    noteAlertsText: ({ open, acked, resolved }) => `${open} open, ${acked} acknowledged, ${resolved} resolved this cycle.`,
    noteAccess: 'Access',
    noteAccessText: ({ noMfa, stale, keys }) => `${noMfa} elevated account(s) without MFA, ${stale} stale account(s), ${keys} access key(s) past a year old.`,
    chartTitle: 'Spend, last seven months',
    downloads: 'Downloads',
    dlReview: 'Full monthly review',
    dlReviewSub: 'One row per section with the headline figures',
    dlInventory: 'Resource inventory',
    dlRows: ({ n }) => `${n} rows`,
    dlCost: 'Cost by service and month',
    dlMonths: ({ n }) => `${n} months`,
    dlWaste: 'Idle and waste',
    dlFindings: ({ n }) => `${n} findings`,
    dlAccess: 'Access review',
    dlAccounts: ({ n }) => `${n} accounts`,
    dlUptime: 'Uptime, 30 days',
    dlServices: ({ n }) => `${n} services`,
    generated: ({ id }) => `Review ${id} generated`,
    listTitle: 'Generated reviews',
    emptyTitle: 'No reviews yet',
    emptyBody: 'Generate one to freeze this month’s numbers. Saved reviews survive a reload.',
    thReview: 'Review',
    thMonth: 'Month',
    thSpend: 'Spend',
    thWaste: 'Waste',
    thUptime: 'Uptime',
    thOpen: 'Open alerts',
    thCreated: 'Created',
    downloadLabel: ({ id }) => `Download ${id}`,
    deleteLabel: ({ id }) => `Delete ${id}`,
    deleteBody: ({ id }) => `Delete review ${id}?`,
    deleteTitle: 'Delete review',
    deleteOk: 'Delete',
    deleted: 'Review deleted',
    downloaded: 'Review downloaded',
    csvRows: {
      section: 'Section', metric: 'Metric', value: 'Value',
      spend: 'Spend', runRate: 'Run rate USD', mtd: 'Month to date USD',
      change: ({ month }) => `Change vs ${month} USD`, runRateSar: 'Run rate SAR',
      byEnv: 'Spend by environment', byTeam: 'Spend by team',
      estate: 'Estate', resources: 'Resources', untagged: 'Untagged resources',
      waste: 'Waste', findings: 'Findings', saving: 'Monthly saving available USD',
      inPlan: 'In cleanup plan', reliability: 'Reliability', fleet: 'Fleet uptime 30d %',
      belowTarget: 'Services below target', alerts: 'Alerts', open: 'Open',
      acked: 'Acknowledged', resolved: 'Resolved', access: 'Access',
      accounts: 'Accounts', noMfa: 'Elevated without MFA', stale: 'Stale accounts',
      review: 'Review', month: 'Month', author: 'Author', created: 'Created',
      changePrev: 'Change vs previous month USD', wasteAvail: 'Waste available USD',
      plannedFindings: 'Findings in cleanup plan', fleetPct: 'Fleet uptime %',
      openAlerts: 'Open alerts',
    },
  },

  /* ---------- Stackview Insight ----------
     The assistant reads and writes English: its intent patterns, the
     suggestion chips and the `ask` lines below are the sentences a reader
     types at it, so they stay in Latin on both sides. What is translated
     here is everything the panel says on its own. */
  agent: {
    tag: 'Demo agent · reads this workspace only',
    greeting: ({ resources, alerts, users }) => `I read the estate in front of you — ${resources} resources, ${alerts} alerts, ${users} accounts — and answer with the numbers that are on screen right now.\n\nI can also do the work: acknowledge alerts, build the cleanup plan, stop a resource, move an owner, fix an account, tag what is unallocated. I show you exactly what I am about to touch and wait for you to press.\n\nAsk **"what can you do?"**, try one of these, or ask in your own words.`,
    note: 'Demo agent — every answer is assembled locally from the sample estate in this app. No network calls, no model.',
    fallbacks: [
      'I only answer from this workspace. Ask me what is idle, where the biggest cost jump came from, which admins have no MFA, or tell me to acknowledge everything critical from last night.',
      'That one is outside the demo data. I can pull spend by environment or team, the projected month end, the alert queue, uptime against SLO, or the access review — and I can change any of it on your say so.',
      'I could not match that to anything in the estate. Try "what is safe to switch off", "tag every untagged resource with its owner", or "which accounts are stale".',
      'No match in the current data. Ask "what can you do?" for the six things I can change, or ask me anything about cost, waste, alerts, uptime, access and inventory.',
    ],
    ui: {
      openLabel: ({ name }) => `Open ${name}`,
      fabTitle: ({ name }) => `${name} — ask about this workspace`,
      clear: 'Clear conversation',
      close: 'Close',
      placeholder: 'Ask something…',
      send: 'Send',
      you: 'You',
      working: 'Working…',
      done: 'Done.',
      answerError: 'That query hit an edge of the demo data set. Try one of the suggestions.',
      actionError: 'That could not be applied — the record may have changed since I read it.',
      applied: 'change applied to this browser',
      searched: 'searched the workspace index',
      seconds: ({ s }) => `${s}s`,
    },
    /* the six things it can change, shown in the About panel and in the
       assistant's own "what can you do?" answer */
    actions: {
      alerts: {
        title: 'Work the alert queue',
        does: 'names the critical alerts opened in the overnight window and counts them, then on confirmation acknowledges them as Aravind Menon, writes a timeline entry on each and reports the queue before and after. "Mute the certificate alert for 24 hours" does the single one.',
        screen: 'Alerts',
      },
      plan: {
        title: 'Build the cleanup plan',
        does: 'lists the three findings it will pick up with their monthly saving, then adds them and reports the plan going from one figure to another, with the yearly number.',
        screen: 'Cost → Idle and waste',
      },
      stop: {
        title: 'Stop a resource',
        does: 'reads the resource, its environment, owner and monthly draw, then stops it. Anything in production has to be confirmed on a button that says so, and it names the service that resource backs before you press.',
        screen: 'Resources',
      },
      reassign: {
        title: 'Reassign ownership',
        does: 'moves the owner and the Owner tag, and reports how much monthly spend moved from one person to the other.',
        screen: 'Resources · Access',
      },
      account: {
        title: 'Fix an account',
        does: 'turns the second factor on and reports MFA coverage before and after. "Start offboarding for Ashraf Kunhi" opens the seven step checklist instead.',
        screen: 'Access',
      },
      tag: {
        title: 'Tag what is unallocated',
        does: 'applies Owner, CostCentre and ManagedBy to the resources that have none, and reports how much monthly spend moved out of unallocated.',
        screen: 'Resources · Cost → By team',
      },
    },
  },
};

const AR = {
  /* ---------- الهيكل ---------- */
  app: {
    name: 'stackview',
    tag: 'رؤية شاملة للبنية التقنية',
    tenant: 'الجهة',
    docTitle: ({ title }) => `${title} · stackview`,
  },

  routes: {
    overview: { title: 'نظرة عامة', sub: 'البنية في لمحة' },
    alerts: { title: 'التنبيهات', sub: 'المفتوحة والمستلَمة' },
    uptime: { title: 'التوافر', sub: 'آخر 30 يوماً' },
    resources: { title: 'الموارد', sub: 'الجرد' },
    cost: { title: 'التكلفة', sub: 'الإنفاق والهدر' },
    access: { title: 'الوصول', sub: 'الحسابات والصلاحيات' },
    reports: { title: 'التقارير', sub: 'المراجعة الشهرية' },
  },
  navgroups: { Monitor: 'المراقبة', Estate: 'البنية', Governance: 'الحوكمة' },

  chrome: {
    primaryNav: 'التنقل الرئيسي',
    openNav: 'فتح قائمة التنقل',
    closePanel: 'إغلاق اللوحة',
    railCollapse: 'طي الشريط الجانبي',
    railExpand: 'توسيع الشريط الجانبي',
    tone: 'لون الشريط الجانبي',
    devicePreview: 'معاينة على جهاز',
    phonePreview: 'معاينة بمقاس الهاتف',
    desktopPreview: 'العودة إلى مقاس سطح المكتب',
    backToDesktop: 'العودة إلى سطح المكتب',
    phoneFrameTitle: 'Stackview داخل إطار هاتف بمقاس 390 في 844',
    phoneSize: 'معاينة الهاتف · 390 × 844',
    themeToLight: 'التحويل إلى الوضع الفاتح',
    themeToDark: 'التحويل إلى الوضع الداكن',
    navOpenSuffix: ({ n }) => `(${n} مفتوح)`,
    aboutDemo: 'عن هذا العرض التجريبي',
    aboutPillTitle: 'كل رقم ومورد وحساب وتنبيه هنا بيانات تجريبية من نسج الخيال، ولا يغادر شيء منها متصفحك. افتحها للتفاصيل.',
    aboutPillLong: 'عن هذا ',
    aboutPillShort: 'العرض',
    reset: 'إعادة تعيين البيانات التجريبية',
    resetBody: 'هذا يمسح كل تغيير أجريته في هذا العرض — التنبيهات المستلَمة وخطط التنظيف وتقدّم إنهاء الخدمة والتقارير المولَّدة — ويعيد بناء البنية التجريبية من جديد.',
    resetOk: 'إعادة التعيين',
    resetDone: 'أُعيد تعيين البيانات التجريبية',
    site: 'nasvih.in',
    siteLabel: 'nasvih.in — يفتح في تبويب جديد',
    github: 'GitHub',
    githubLabel: 'GitHub — يفتح مستودع الشيفرة في تبويب جديد',
    sourceOnGithub: 'الشيفرة على GitHub',
    sourceOnGithubLabel: 'الشيفرة على GitHub — تفتح في تبويب جديد',
    viewErrorTitle: 'تعذّر رسم هذه الشاشة',
    viewErrorBody: 'أعد تعيين البيانات التجريبية من الشريط الجانبي لإعادة بناء البنية التجريبية.',
  },

  ui: {
    confirmTitle: 'تأكيد',
    confirmOk: 'تأكيد',
    cancel: 'إلغاء',
    close: 'إغلاق',
    install: 'تثبيت التطبيق',
    installTitle: ({ app }) => `تثبيت ${app} على هذا الجهاز`,
    installed: ({ app }) => `تم تثبيت ${app}. سيفتح في نافذته الخاصة من الآن.`,
    installDismissed: 'أُلغي التثبيت — الزر يبقى هنا إن غيّرت رأيك.',
    installIOS: 'على iPhone وiPad: اضغط «مشاركة» ثم «إضافة إلى الشاشة الرئيسية».',
    installOther: 'افتح قائمة المتصفح واختر «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية».',
  },

  time: {
    now: 'الآن',
    mins: ({ n }) => `قبل ${n} د`,
    hours: ({ n }) => `قبل ${n} س`,
    days: ({ n }) => `قبل ${n} ي`,
    today: 'اليوم',
    daysAgoShort: ({ n }) => `قبل ${n} ي`,
  },

  states: {
    running: 'يعمل', available: 'متاح', degraded: 'متدهور',
    stopped: 'متوقف', unattached: 'غير مرتبط', unassociated: 'غير مقترن',
  },
  envs: { prod: 'إنتاج', staging: 'اختبار', dev: 'تطوير', shared: 'مشترك' },
  sev: { critical: 'حرج', high: 'مرتفع', warning: 'تحذير', info: 'معلومة' },
  alertStatus: { open: 'مفتوح', acked: 'مستلَم', muted: 'مكتوم', resolved: 'مُغلق' },
  roles: {
    Admin: 'مسؤول', 'Power user': 'مستخدم متقدم', Developer: 'مطوّر',
    'Read only': 'قراءة فقط', Billing: 'الفوترة',
  },
  providers: { aws: 'AWS', azure: 'Azure', onprem: 'محلي' },
  directories: { 'AWS IAM': 'AWS IAM', 'Entra ID': 'Entra ID', 'on-prem AD': 'AD محلي' },
  teams: {
    Platform: 'المنصة', Payments: 'المدفوعات', Data: 'البيانات',
    'Retail Apps': 'تطبيقات التجزئة', 'Facilities IT': 'تقنية المرافق',
  },
  serviceGroups: {
    Compute: 'الحوسبة', Kubernetes: 'Kubernetes', Databases: 'قواعد البيانات',
    Storage: 'التخزين', Network: 'الشبكة', 'Backup & DR': 'النسخ الاحتياطي والتعافي',
    'On-prem & DC': 'المعدات ومراكز البيانات', Integration: 'التكامل',
    'Security & identity': 'الأمن والهوية', Observability: 'القياس والرصد',
    Other: 'أخرى',
  },
  sources: { 'Cost guard': 'حارس التكلفة' },
  months: {
    Jan: 'يناير', Feb: 'فبراير', Mar: 'مارس', Apr: 'أبريل', May: 'مايو', Jun: 'يونيو',
    Jul: 'يوليو', Aug: 'أغسطس', Sep: 'سبتمبر', Oct: 'أكتوبر', Nov: 'نوفمبر', Dec: 'ديسمبر',
  },
  tiers: { 'Tier 1': 'المستوى 1', 'Tier 2': 'المستوى 2', 'Tier 3': 'المستوى 3' },
  uptimeServices: {
    'Checkout API': 'واجهة الدفع',
    'Orders API': 'واجهة الطلبات',
    Storefront: 'واجهة المتجر',
    'Payments webhook': 'ويب هوك المدفوعات',
    'Warehouse sync': 'مزامنة المستودع',
    'Admin console': 'لوحة الإدارة',
    'Facilities VPN': 'شبكة VPN للمرافق',
    'Mail relay': 'مُرحِّل البريد',
  },
  offboard: [
    'تعطيل حساب الدليل وإنهاء الجلسات النشطة',
    'إيقاف مفاتيح الوصول السحابية وحذفها',
    'الإزالة من قوائم السماح في VPN وخوادم الوصول',
    'نقل ملكية الموارد الموسومة باسم الموظف',
    'الإزالة من مجموعات المستودعات وخطوط النشر',
    'استلام الحاسوب المحمول وأي مفتاح مادي',
    'أرشفة صندوق البريد وضبط قاعدة تحويل',
  ],

  activity: {
    seedVolumes: ({ n }) => `رصد حارس التكلفة ${arN(n, { one: 'وحدة تخزين واحدة غير مرتبطة', two: 'وحدتَي تخزين غير مرتبطتين', few: `${n} وحدات تخزين غير مرتبطة`, many: `${n} وحدة تخزين غير مرتبطة` })}`,
    seedScaled: 'توسّع eks-prod-ng-general من ثلاث عقد إلى أربع',
    seedReview: ({ n }) => `فُتحت مراجعة الوصول لـ ${arN(n, { one: 'حساب راكد واحد', two: 'حسابين راكدين', few: `${n} حسابات راكدة`, many: `${n} حساباً راكداً` })}`,
    alertsAcked: ({ n }) => `استُلم ${arN(n, { one: 'تنبيه واحد', two: 'تنبيهان', few: `${n} تنبيهات`, many: `${n} تنبيهاً` })}`,
    alertAcked: ({ id }) => `استُلم ${id}`,
    alertMuted: ({ id }) => `كُتم ${id}`,
    alertUnmuted: ({ id }) => `أُلغي كتم ${id}`,
    alertResolved: ({ id }) => `أُغلق ${id}`,
    planAdded: ({ name }) => `أُضيف ${name} إلى خطة التنظيف`,
    planRemoved: ({ name }) => `أُزيل ${name} من خطة التنظيف`,
    reassigned: ({ name, to }) => `نُقلت ملكية ${name} إلى ${to}`,
    stopped: ({ name }) => `أُوقف ${name}`,
    started: ({ name }) => `شُغّل ${name}`,
    deleted: ({ name, money }) => `حُذف ${name} — تحرّر ${money} شهرياً`,
    offboardStarted: ({ name }) => `بدأ إنهاء خدمة ${name}`,
    offboarded: ({ name }) => `أُنهيت خدمة ${name} وعُطّل حسابه`,
    roleChanged: ({ name, from, to }) => `تغيّرت صلاحية ${name} من ${from} إلى ${to}`,
    mfaOn: ({ name }) => `فُرض MFA على ${name}`,
    mfaOff: ({ name }) => `أُزيل شرط MFA عن ${name}`,
    keyRotated: ({ name }) => `دُوّر مفتاح الوصول لـ ${name}`,
    maintOn: ({ name, date }) => `أُعيد تصنيف ${name} في ${date} كصيانة مخطّطة`,
    maintOff: ({ name, date }) => `أُعيد ${name} في ${date} إلى غير المخطّط`,
    reviewGenerated: ({ id, month }) => `وُلّدت المراجعة الشهرية ${id} عن ${month}`,
    aiAcked: ({ n }) => `استُلم ${arN(n, { one: 'تنبيه واحد', two: 'تنبيهان', few: `${n} تنبيهات`, many: `${n} تنبيهاً` })} من المساعد`,
    aiMuted: ({ n }) => `كُتم ${arN(n, { one: 'تنبيه واحد', two: 'تنبيهان', few: `${n} تنبيهات`, many: `${n} تنبيهاً` })} من المساعد`,
    aiUnmuted: ({ n }) => `أُلغي كتم ${arN(n, { one: 'تنبيه واحد', two: 'تنبيهين', few: `${n} تنبيهات`, many: `${n} تنبيهاً` })} من المساعد`,
    aiPlan: ({ n }) => `أُضيفت ${arN(n, { one: 'نتيجة واحدة', two: 'نتيجتان', few: `${n} نتائج`, many: `${n} نتيجة` })} إلى خطة التنظيف من المساعد`,
    aiPlanOne: ({ name }) => `أُضيف ${name} إلى خطة التنظيف من المساعد`,
    aiStopped: ({ name }) => `أُوقف ${name} من المساعد`,
    aiStoppedProd: ({ name }) => `أُوقف ${name} من المساعد (إنتاج)`,
    aiStarted: ({ name }) => `شُغّل ${name} من المساعد`,
    aiReassigned: ({ name, from, to }) => `نقل المساعد ملكية ${name} من ${from} إلى ${to}`,
    aiOffboard: ({ name }) => `بدأ إنهاء خدمة ${name} من المساعد`,
    aiMfa: ({ n }) => `فُرض MFA على ${arN(n, { one: 'حساب واحد', two: 'حسابين', few: `${n} حسابات`, many: `${n} حساباً` })} من المساعد`,
    aiTagged: ({ n }) => `وُسم ${arN(n, { one: 'مورد واحد', two: 'موردان', few: `${n} موارد`, many: `${n} مورداً` })} من المساعد`,
  },
  timeline: {
    opened: 'فُتح التنبيه',
    acked: 'استُلم',
    ackedBulk: 'استُلم ضمن استلام جماعي',
    muted: 'كُتم لمدة 24 ساعة',
    unmuted: 'أُلغي الكتم',
    resolved: 'وُسم كمُغلق',
    aiAcked: 'استُلم من Stackview Insight',
    aiMuted: 'كُتم 24 ساعة من Stackview Insight',
    aiUnmuted: 'أُلغي الكتم من Stackview Insight',
  },

  about: {
    title: 'عن Stackview',
    ok: 'فهمت',
    lead: 'البنية المعروضة على هذه الشاشات — مجموعة Northline ومواردها وموظفوها وفواتيرها — بيانات تجريبية من نسج الخيال.',
    whatTitle: 'ما هذا التطبيق',
    whatText: 'Stackview صورة واحدة لما تشغّله المنشأة وما تدفعه مقابله. يجمع كل مورد — عبر مزوّدي السحابة والخزائن المحلية — في جرد واحد، ثم يقرأ التكلفة فوقه حسب الخدمة والبيئة والفريق. حالة الوصول وMFA والتنبيهات المفتوحة وتوافر الثلاثين يوماً كلها على البنية نفسها، فيصير جواب سؤال «ماذا نشغّل، وكم يكلّف، ومن يستطيع الدخول إليه» شاشة واحدة بدل ثلاث لوحات تحكم.',
    helpTitle: 'أين يفيد المنشأة',
    help: [
      ['جرد واحد', 'لا أحد يفتح ثلاث لوحات تحكم ليجيب عن «ماذا نشغّل». السحابة والمعدات المحلية في الجدول نفسه وبالمرشّحات نفسها.'],
      ['يُكتشف الهدر قبل الفاتورة', 'الموارد الخاملة والمنسية مسرودة مع السبب والمبلغ الشهري، بدل أن تُلاحظ عند إصدار الفاتورة.'],
      ['لكل مورد مالك', 'الملكية ملتصقة بالمورد، فهناك شخص باسمه يُسأل قبل إطفاء أي شيء.'],
      ['مراجعة الوصول مكتوبة سلفاً', 'الحسابات الراكدة والمسؤولون بلا MFA والمفاتيح القديمة مسرودة باستمرار، فتتوقف المراجعة عن كونها سباقاً سنوياً.'],
      ['التنبيهات تترك أثراً', 'الاستلام والكتم مسجّلان على التنبيه نفسه، فيمكن إعادة بناء الحادثة بعد وقوعها.'],
    ],
    realTitle: 'كيف سيعمل على أرض الواقع',
    realText: 'الواجهة نفسها، تقرأ من واجهات المزوّدين ودليل الهوية بدل البيانات التجريبية، مع تحديث الجرد وبنود التكلفة ونتائج الوصول وفق جدول. ما تراه هنا هو الواجهة وسير العمل — لا حساب موصول ولا شيء يُستعلم عنه.',
    demoTitle: 'كيف يعمل هذا العرض',
    demo: [
      ['يمكنك استخدامه فعلاً', 'استلم التنبيهات واكتمها، أوقف الموارد وانقل ملكيتها، اعمل على قائمة الخمول والهدر، شغّل مراجعة الوصول وقائمة إنهاء الخدمة، ولّد مراجعة شهرية. لا شيء في هذه الشاشات للقراءة فقط.'],
      ['بياناتك تبقى على جهازك', 'كل ما تغيّره محفوظ في التخزين المحلي لهذا المتصفح. لا حساب ولا خادم خلفي. «إعادة تعيين البيانات التجريبية» تمسحها، وهي لا تُزامَن بين المتصفحات أو الأجهزة.'],
      ['المساعد محاكاة', 'يجيب Stackview Insight بمطابقة سؤالك مع البيانات التجريبية لهذا التطبيق وحدها. هو عرض للتفاعل لا نموذج موصول، ولا يغادر أي طلب متصفحك.'],
    ],
    askTitle: 'ما الذي يمكن أن تطلبه من المساعد',
    askLead: 'لا يكتفي Stackview Insight بالتقرير. اكتب واحدة من هذه، فيسمّي لك بالضبط ما سيمسّه، ثم ينفّذه حين تضغط الزر — لا قبله.',
    itDoes: ({ does }) => does,
    landsOn: ({ screen }) => `ينتهي عند ${screen}`,
    sourceTitle: 'الشيفرة المصدرية',
    sourceNote: 'نُشرت الشيفرة لتُقرأ وتُشغّل وتُقيَّم. وهي ليست مفتوحة المصدر — نسخها أو تعديلها أو إعادة توزيعها أو نشرها أو استخدامها كبيانات تدريب يحتاج إذناً مكتوباً. راجع ملف LICENSE في المستودع.',
  },

  notif: {
    title: 'الإشعارات',
    panelLabel: 'الإشعارات',
    unreadCount: ({ n, total }) => `${n} غير مقروء من ${total}`,
    nothingOpen: 'لا شيء مفتوح',
    markAll: 'تعليم الكل كمقروء',
    markRead: 'تعليم كمقروء',
    markReadOne: ({ title }) => `تعليم «${title}» كمقروء`,
    closeLabel: 'إغلاق الإشعارات',
    bellUnread: ({ n }) => `الإشعارات، ${n} غير مقروء`,
    bellClear: 'الإشعارات، لا شيء غير مقروء',
    emptyTitle: 'لا شيء يحتاجك',
    emptyBody: 'لا تنبيه حرج مفتوح، والشهر يسير قريباً من الشهر الماضي، وكل حساب ذي صلاحية موسّعة عليه عامل ثانٍ، ولا مفتاح تجاوز السنة. هذه القائمة مبنية من البنية نفسها، فتمتلئ من جديد كلما تغيّرت الأمور.',
    kindCritical: 'تنبيه حرج',
    kindBudget: 'انحراف الميزانية',
    kindMfa: 'بلا MFA',
    kindKey: 'مفتاح قديم',
    kindIdle: 'خامل منذ أسابيع',
    budgetTitle: ({ money, dir, month }) => `نهاية الشهر تسير ${dir} ${month} بمقدار ${money}`,
    budgetAbove: 'فوق',
    budgetBelow: 'تحت',
    budgetBody: ({ projected, prev, pct, dir }) => `${projected} متوقعة مقابل ${prev} الشهر الماضي، بارتفاع ${pct} ${dir}.`,
    budgetUp: 'صعوداً',
    budgetDown: 'نزولاً',
    mfaTitle: ({ name, role }) => `${name} يحمل صلاحية ${role} بلا عامل ثانٍ`,
    mfaBody: ({ directory, team, ago }) => `${directory} · ${team} · آخر دخول ${ago}`,
    keyTitle: ({ name, days }) => `${name} لديه مفتاح وصول عمره ${days} يوماً`,
    keyBody: 'السياسة 90 يوماً. دوّره من لوحة الحساب.',
    idleTitle: ({ name, money }) => `${name} خامل بكلفة ${money} شهرياً`,
  },

  overview: {
    title: ({ org }) => `بنية ${org}`,
    lead: ({ n }) => `${n} مورداً موزّعة على AWS وAzure ومركزَي بيانات. التكاليف معروضة بمعدل الإنفاق للشهر الحالي، ومحوّلة إلى SAR لكيان جدة حيث يلزم.`,
    openCost: 'فتح التكلفة',
    openAlerts: ({ n }) => `${n} تنبيهاً مفتوحاً`,
    statSpend: 'إنفاق هذا الشهر',
    statSpendDelta: ({ projected, sar }) => `${projected} متوقعة عند نهاية الشهر · ${sar}`,
    statResources: 'الموارد',
    statResourcesDelta: ({ running, idle }) => `${running} تعمل · ${idle} خاملة أو غير مرتبطة`,
    statAlerts: 'تنبيهات مفتوحة',
    statAlertsDelta: ({ crit, ago }) => `${crit} حرجة، أقدمها ${ago}`,
    statAlertsClear: 'لا تنبيه حرج مفتوح',
    statUptime: 'التوافر خلال 30 يوماً',
    statUptimeDelta: ({ n }) => `${n} خدمات مرصودة`,
    monthlySpend: 'الإنفاق الشهري',
    vsPrev: ({ sign, pct, month }) => `${sign}${pct}% مقابل ${month}`,
    spendNote: ({ prev, prevTotal, cur, diff, dir }) => `أُغلق ${prev} عند ${prevTotal}. و${cur} يسير ${dir} بمقدار ${diff}.`,
    higher: 'أعلى',
    lower: 'أدنى',
    byEnv: 'حسب البيئة',
    nonProd: ({ pct }) => `ما دون الإنتاج يمثل ${pct} من الفاتورة.`,
    provSub: ({ n, regions }) => `${n} مورداً · ${regions} مناطق`,
    wasteTitle: 'الخمول والهدر',
    openFinder: 'فتح الكاشف',
    wasteBannerLead: ({ money }) => `${money} شهرياً`,
    wasteBannerMid: ' عالقة في ',
    wasteBannerTail: ({ n, pct }) => ` مورداً خاملاً أو غير مرتبط أو مفرط الحجم. أي ${pct} من معدل الإنفاق.`,
    thResource: 'المورد',
    thWhy: 'السبب',
    thSaving: 'التوفير',
    latestAlerts: 'أحدث التنبيهات',
    allAlerts: 'كل التنبيهات',
    nothingOpen: 'لا شيء مفتوح',
    nothingOpenBody: 'كل تنبيه استُلم أو كُتم.',
    hygiene: 'سلامة الوصول',
    review: 'مراجعة',
    hygieneNoMfa: 'مسؤولون بلا MFA',
    hygieneStale: 'حسابات راكدة',
    hygieneKeys: 'مفاتيح أقدم من سنة',
    hygieneUntagged: 'موارد بلا وسوم',
    hygieneNote: ({ names }) => `${names} يحملون صلاحيات موسّعة بلا عامل ثانٍ.`,
    recentActivity: 'النشاط الأخير',
  },

  alerts: {
    lead: 'كل ما يُطلق عبر CloudWatch وAzure Monitor وAlertmanager وZabbix وNagios وبرنامج النسخ الاحتياطي، في طابور واحد. استلام التنبيه يسجّل من التقطه.',
    export: 'تصدير',
    exported: 'صُدّرت التنبيهات',
    csv: ['Id', 'Severity', 'Title', 'Resource', 'Service', 'Source', 'Opened', 'Status', 'Acknowledged by'],
    ackAll: 'استلام كل المفتوح',
    nothingLeftOpen: 'لم يبق شيء مفتوح',
    ackAllBody: ({ n, me }) => `استلام ${n} تنبيهاً مفتوحاً باسم ${me}. تبقى في الطابور حتى تُغلق.`,
    ackAllTitle: 'استلام الكل',
    ackAllOk: 'استلام',
    ackedToast: ({ n }) => `استُلم ${arN(n, { one: 'تنبيه واحد', two: 'تنبيهان', few: `${n} تنبيهات`, many: `${n} تنبيهاً` })}`,
    statOpen: 'مفتوحة',
    statOpenOldest: ({ ago }) => `أقدمها ${ago}`,
    statOpenClear: 'الطابور خالٍ',
    statCritical: 'حرجة',
    statCriticalSub: 'تستدعي مهندس المناوبة',
    statAcked: 'مستلَمة',
    statAckedSub: 'التُقطت ولم تُصلَح',
    statMuted: 'مكتومة',
    statMutedSub: 'مخفية عن الطابور',
    filterSeverity: 'الخطورة',
    filterStatus: 'الحالة',
    all: 'الكل',
    any: 'أي حالة',
    chipAcked: 'مستلَم',
    emptyTitle: 'لا شيء هنا',
    emptyBody: 'لا تنبيه يطابق هذا المرشّح. جرّب حالة «أي حالة».',
    meta: ({ source, resource, date, time, ago }) => `${source} · ${resource} · فُتح ${date} ${time} (${ago})`,
    ackedBy: ({ who }) => ` · استلمه ${who}`,
    ack: 'استلام',
    mute24: 'كتم 24 س',
    unmute: 'إلغاء الكتم',
    resolve: 'إغلاق',
    timeline: 'المسار الزمني',
    toastAcked: 'استُلم التنبيه',
    toastMuted: 'كُتم التنبيه',
    toastUnmuted: 'أُلغي كتم التنبيه',
    toastResolved: 'أُغلق التنبيه',
    kvId: 'رقم التنبيه',
    kvService: 'الخدمة',
    kvResource: 'المورد',
    kvOpened: 'فُتح في',
    kvAge: 'العمر',
    kvAckedBy: 'استلمه',
    nobodyYet: 'لا أحد بعد',
    notePlaceholder: 'أضف ملاحظة إلى المسار الزمني',
    noteLabel: 'ملاحظة على المسار الزمني',
    noteEmpty: 'اكتب الملاحظة أولاً',
    noteAdded: 'أُضيفت الملاحظة',
    add: 'إضافة',
  },

  cost: {
    lead: 'معدل الإنفاق للشهر الحالي، مقسوماً بثلاث طرق. المعدات المحلية مستهلَكة على عمرها، ليصير مقارنة خادم في مركز البيانات بمثيل سحابي أمراً منصفاً.',
    exportBreakdown: 'تصدير التفصيل',
    exportedBreakdown: 'صُدّر التفصيل',
    csvBreakdown: ['Month', 'Service', 'USD'],
    tileRunRate: 'معدل الإنفاق',
    tileRunRateSub: ({ sar }) => `${sar} على سعر 3.75`,
    tileMtd: 'منذ بداية الشهر',
    tileMtdSub: ({ day, days }) => `اليوم ${day} من ${days}`,
    tileMover: 'أكبر متحرّك',
    tileMoverSub: ({ sign, money, month }) => `${sign}${money} مقابل ${month}`,
    tileWaste: 'الخمول والهدر',
    tileWasteSub: ({ n }) => `${n} نتيجة مفتوحة`,
    banner: 'هذه الأرقام بيانات تجريبية من نسج الخيال لا فاتورة حقيقية. لا شيء يُقرأ من حساب فوترة سحابي، وخطة التنظيف محفوظة في هذا المتصفح وحده.',
    tabService: 'حسب الخدمة',
    tabEnv: 'حسب البيئة',
    tabTeam: 'حسب الفريق',
    tabWaste: 'الخمول والهدر',
    trend: 'اتجاه سبعة أشهر',
    trendRange: ({ from, to }) => `${from} إلى ${to}`,
    thGroup: 'مجموعة الخدمة',
    thShare: 'الحصة',
    thChange: 'التغيّر',
    thTotal: 'الإجمالي',
    jumpLead: ({ label, money }) => `${label} أكبر قفزة هذا الشهر، بزيادة ${money}. `,
    jumpK8s: 'انتقل eks-prod-ng-general من ثلاث عقد m6i.2xlarge إلى أربع في السادس من الشهر، والعقدة الزائدة لم تنزل منذ ذلك الحين.',
    jumpOther: 'راجع موارد هذه المجموعة بحثاً عن تغيّر في الحجم أو نشر جديد.',
    runRateBy: ({ label }) => `معدل الإنفاق حسب ${label}`,
    groupEnv: 'البيئة',
    groupTeam: 'الفريق',
    groupEnvLower: 'البيئة',
    groupTeamLower: 'الفريق',
    thResources: 'الموارد',
    thMonthly: 'شهرياً',
    thWaste: 'الهدر',
    thProviders: 'المزوّدون',
    savingTotal: 'إجمالي التوفير الممكن',
    savingSub: ({ n, pct, sar }) => `${n} نتيجة · ${pct} من معدل الإنفاق · ${sar} شهرياً`,
    inPlan: 'ضمن خطة التنظيف',
    inPlanSub: ({ n, total }) => `${n} من ${total} التُقطت`,
    nothingFlagged: 'لا شيء مرصود',
    nothingFlaggedBody: 'كل نتيجة صُرف النظر عنها أو أن المورد لم يعد موجوداً. أعد تعيين البيانات التجريبية لإعادتها.',
    doThis: 'الإجراء: ',
    addToPlan: 'إضافة إلى خطة التنظيف',
    inPlanBtn: 'ضمن خطة التنظيف',
    removedFromPlan: 'أُزيل من الخطة',
    addedToPlan: 'أُضيف إلى خطة التنظيف',
    dismiss: 'صرف النظر',
    dismissed: 'صُرف النظر عن النتيجة',
    openInInventory: 'فتحه في الجرد',
    dismissedNote: ({ n, names }) => `${arN(n, { one: 'نتيجة واحدة صُرف النظر عنها', two: 'نتيجتان صُرف النظر عنهما', few: `${n} نتائج صُرف النظر عنها`, many: `${n} نتيجة صُرف النظر عنها` })}: ${names}`,
    restore: 'استعادة',
    restored: 'أُعيدت النتائج المصروف عنها',
    planTitle: 'خطة التنظيف',
    exportPlan: 'تصدير الخطة',
    exportedPlan: 'صُدّرت خطة التنظيف',
    csvPlan: ['Resource', 'Provider', 'Environment', 'Owner', 'Monthly saving USD', 'Reason', 'Action'],
    csvTotal: 'Total',
    planNote: ({ month, year }) => `سلّم هذه القائمة إلى الملاك. تنفيذها كاملة يخصم ${month} شهرياً من الفاتورة، أي ${year} في السنة.`,
    perMonth: ({ money }) => `${money}/شهر`,
  },

  resources: {
    lead: 'كل ما تشغّله المجموعة، في قائمة واحدة. التكاليف هي معدل الإنفاق للشهر الحالي لكل مورد، بما فيها المعدات المحلية مستهلَكة على دورة تجديدها.',
    exportCsv: 'تصدير CSV',
    exported: 'صُدّر الجرد',
    csv: ['Name', 'Provider', 'Type', 'Size', 'Environment', 'Region', 'State', 'Monthly USD', 'Owner', 'Team', 'Tagged'],
    yes: 'yes',
    no: 'no',
    banner: 'هذه البنية بيانات تجريبية من نسج الخيال. لا حساب سحابي ولا مركز بيانات موصول، وأي تغيير تجريه هنا محفوظ في هذا المتصفح وحده.',
    searchPlaceholder: 'ابحث بالاسم أو النوع أو المنطقة أو المالك أو الوسم',
    searchLabel: 'البحث في الموارد',
    all: 'الكل',
    filterProvider: 'المزوّد',
    filterEnv: 'البيئة',
    filterState: 'الحالة',
    filterTeam: 'الفريق',
    count: ({ n, total, money }) => `${n} من ${total} · ${money}/شهر`,
    emptyTitle: 'لا مورد يطابق',
    emptyBody: 'أزل مرشّحاً أو ابحث عن شيء آخر.',
    thResource: 'المورد',
    thType: 'النوع',
    thEnv: 'البيئة',
    thRegion: 'المنطقة',
    thState: 'الحالة',
    thMonthly: 'شهرياً',
    thOwner: 'المالك',
    thTags: 'الوسوم',
    sortBy: ({ label }) => `الترتيب حسب ${label}`,
    openRow: ({ name }) => `فتح ${name}`,
    tagCount: ({ n }) => `${n} وسوم`,
    untagged: 'بلا وسوم',
    kvType: 'النوع',
    kvRegion: 'المنطقة',
    kvCost: 'التكلفة الشهرية',
    kvGroup: 'مجموعة الخدمة',
    kvOwner: 'المالك',
    kvTeam: 'الفريق',
    kvAge: 'العمر',
    kvAgeVal: ({ n }) => `${n} يوماً`,
    kvLastMetric: 'آخر قياس',
    kvLastMetricVal: ({ n }) => `قبل ${n} س`,
    utilTitle: 'الاستخدام، متوسط 30 يوماً',
    cpu: 'المعالج',
    memory: 'الذاكرة',
    disk: 'القرص',
    netOut: 'الصادر عبر الشبكة',
    tags: 'الوسوم',
    noTags: 'لا وسوم. لن يظهر هذا المورد في أي تقرير توزيع تكلفة.',
    tagBanner: 'ينقصه Owner وCostCentre وManagedBy. سياسة الوسم تعدّه إنفاقاً غير موزّع.',
    wasteFinding: 'نتيجة هدر',
    suggestedAction: 'الإجراء المقترح: ',
    inPlan: 'ضمن خطة التنظيف',
    addToPlan: 'إضافة إلى خطة التنظيف',
    addedToPlan: 'أُضيف إلى خطة التنظيف',
    removedFromPlan: 'أُزيل من خطة التنظيف',
    dismissFinding: 'صرف النظر عن النتيجة',
    dismissed: 'صُرف النظر عن النتيجة',
    noteTitle: 'ملاحظة تشغيلية',
    notePlaceholder: 'لماذا يوجد هذا المورد، ومن طلبه، ومتى يمكن إيقافه…',
    saveNote: 'حفظ الملاحظة',
    noteSaved: 'حُفظت الملاحظة',
    actions: 'إجراءات',
    reassignLabel: 'نقل الملكية',
    ownerField: 'المالك',
    reassign: 'نقل الملكية',
    ownerUpdated: 'حُدّث المالك',
    startResource: 'تشغيل المورد',
    stopResource: 'إيقاف المورد',
    stopProdBody: ({ name }) => `${name} مورد إنتاج. إيقافه في هذا العرض سيظهره متوقفاً في كل مكان، بما في ذلك التوافر والتكلفة.`,
    stopProdTitle: 'إيقاف مورد إنتاج',
    stopProdOk: 'أوقفه',
    toastStopped: ({ name }) => `أُوقف ${name}`,
    toastStarted: ({ name }) => `شُغّل ${name}`,
    deleteResource: 'حذف المورد',
    deleteBody: ({ name, money }) => `إزالة ${name} من الجرد وإيقاف رسم ${money} الشهري.`,
    deleteTitle: 'حذف المورد',
    deleteOk: 'حذف',
    toastDeleted: ({ name }) => `حُذف ${name}`,
  },

  access: {
    lead: 'حسابات الأشخاص وحسابات الخدمة عبر AWS IAM وEntra ID والدليل المحلي. يُعدّ الحساب راكداً بعد 60 يوماً بلا تسجيل دخول.',
    exportReview: 'تصدير المراجعة',
    exported: 'صُدّرت مراجعة الوصول',
    csv: ['Name', 'Email', 'Team', 'Role', 'Directory', 'MFA', 'Last login', 'Days since login', 'Key age days', 'Status'],
    yes: 'yes',
    no: 'no',
    searchPlaceholder: 'ابحث بالاسم أو البريد أو الفريق',
    searchLabel: 'البحث في الحسابات',
    fEveryone: 'الجميع',
    fElevated: 'صلاحيات موسّعة',
    fNoMfa: 'بلا MFA',
    fStale: 'راكدة',
    fService: 'حسابات خدمة',
    fOffboarding: 'إنهاء خدمة',
    statAccounts: 'الحسابات',
    statAccountsSub: ({ n }) => `${n} حسابات خدمة`,
    statMfa: 'تغطية MFA',
    statMfaSub: ({ n }) => `${n} بلا عامل ثانٍ`,
    statNoMfa: 'مسؤولون بلا MFA',
    statClear: 'لا شيء',
    statStale: 'حسابات راكدة',
    statStaleSub: 'بلا تسجيل دخول منذ 60 يوماً أو أكثر',
    emptyTitle: 'لا حساب يطابق',
    emptyBody: 'جرّب مرشّحاً آخر.',
    thAccount: 'الحساب',
    thRole: 'الصلاحية',
    thDirectory: 'الدليل',
    thMfa: 'MFA',
    thLastLogin: 'آخر دخول',
    thKey: 'مفتاح الوصول',
    thStatus: 'الحالة',
    openRow: ({ name }) => `فتح ${name}`,
    svc: 'SVC',
    on: 'مفعّل',
    off: 'معطّل',
    statusActive: 'نشط',
    statusStale: 'راكد',
    statusService: 'خدمة',
    statusDisabled: 'معطّل',
    statusOffboarding: 'إنهاء خدمة',
    mfaOn: 'MFA مفعّل',
    mfaOff: 'MFA معطّل',
    kvEmail: 'البريد',
    kvTeam: 'الفريق',
    kvLastLogin: 'آخر دخول',
    kvKeyAge: 'عمر مفتاح الوصول',
    kvKeyAgeVal: ({ n }) => `${n} يوماً`,
    noKey: 'لا مفتاح',
    kvOwned: 'الموارد المملوكة',
    kvStatus: 'الحالة',
    noMfaBanner: 'لا عامل ثانٍ على هذا الحساب. ',
    noMfaElevated: 'وهو يحمل صلاحية موسّعة، فهذا أول ما يُصلَح في المراجعة.',
    noMfaOther: 'افرضه قبل إغلاق مراجعة الوصول القادمة.',
    keyBanner: ({ n }) => `عمر مفتاح الوصول ${n} يوماً. السياسة 90 يوماً.`,
    owns: 'يملك',
    offboarding: 'إنهاء الخدمة',
    offboardLead: 'بدء إنهاء الخدمة يفتح قائمة من سبع خطوات ويضع الحساب تحت المراجعة. لا يُحذف شيء في هذا العرض.',
    startOffboard: 'بدء إنهاء الخدمة',
    offboardStarted: 'بدأ إنهاء الخدمة',
    completeOffboard: 'إتمام إنهاء الخدمة',
    completeBody: ({ name, n }) => `إغلاق إنهاء خدمة ${name}. سيظهر الحساب معطّلاً وتبقى موارده البالغة ${n} مرصودة حتى تُنقل ملكيتها.`,
    completeTitle: 'إتمام إنهاء الخدمة',
    completeOk: 'إتمام',
    offboardComplete: 'اكتمل إنهاء الخدمة',
    cancel: 'إلغاء',
    offboardCancelled: 'أُلغي إنهاء الخدمة',
    actions: 'إجراءات',
    changeRole: 'تغيير الصلاحية',
    roleField: 'الصلاحية',
    apply: 'تطبيق',
    roleUpdated: 'حُدّثت الصلاحية',
    removeMfa: 'إزالة شرط MFA',
    enforceMfa: 'فرض MFA',
    mfaRemoved: 'أُزيل شرط MFA',
    mfaEnforced: 'فُرض MFA',
    rotateKey: 'تدوير مفتاح الوصول',
    keyRotated: 'دُوّر مفتاح الوصول',
  },

  uptime: {
    lead: 'ثلاثون يوماً من التوافر اليومي لكل خدمة. كل مربّع يوم واحد؛ مرّر عليه أو ركّز عليه لترى الأرقام. الأيام الموسومة كصيانة مخطّطة تُستثنى من ميزانية الخطأ.',
    allTiers: 'كل المستويات',
    word: { up: 'يعمل', deg: 'متدهور', down: 'انقطاع', maint: 'صيانة مخطّطة' },
    legend: 'المفتاح',
    statFleet: 'توافر الأسطول',
    statFleetSub: ({ n }) => `${n} خدمات مرصودة`,
    statDown: 'الانقطاع خلال 30 يوماً',
    statDownVal: ({ n }) => `${n} د`,
    statDownSub: 'باستثناء الصيانة المخطّطة',
    statBelow: 'دون SLO',
    statBelowClear: 'كل خدمة داخل هدفها',
    statWorst: 'أسوأ يوم',
    statWorstSub: 'أكبر خسارة في يوم واحد',
    svcSub: ({ tier, slo, resource }) => `${tier} · الهدف ${slo}% · ${resource}`,
    insideTarget: 'داخل الهدف',
    belowTarget: 'دون الهدف',
    stripLabel: ({ name }) => `الحالة اليومية لـ ${name}، آخر 30 يوماً`,
    dayTitle: ({ date, word, mins }) => `${date} — ${word}${mins ? `، ${mins} دقيقة ضائعة` : ''}`,
    dayLabel: ({ date, word }) => `${date} ${word}`,
    range: ({ from }) => `${from} ← اليوم`,
    badDays: ({ n, mins }) => `${arN(n, { one: 'يوم سيئ واحد', two: 'يومان سيئان', few: `${n} أيام سيئة`, many: `${n} يوماً سيئاً` })}، ${mins} دقيقة ضائعة`,
    noIncidents: 'لا حوادث',
    budget: ({ used, total }) => `استُهلك ${used} من ميزانية خطأ قدرها ${total} دقيقة`,
    emptyTier: 'لا خدمات في هذا المستوى',
    kvService: 'الخدمة',
    kvDate: 'التاريخ',
    kvAvailability: 'التوافر',
    kvMins: 'الدقائق الضائعة',
    kvBacking: 'المورد الداعم',
    kvTarget: 'الهدف',
    probeNote: ({ mins, date }) => `سجّل المسبار ${mins} دقيقة خارج الهدف في ${date}. قارنها بطابور التنبيهات في تلك النافذة قبل كتابة ملاحظة المراجعة.`,
    probeClear: 'لا إخفاقات مسبار مسجّلة في هذا اليوم.',
    classification: 'التصنيف',
    classificationNote: 'الصيانة المخطّطة مستثناة من ميزانية الخطأ ومن رقم الأسطول في النظرة العامة.',
    markMaint: 'وسمه كصيانة مخطّطة',
    markedMaint: 'موسوم كصيانة مخطّطة',
    toastMaint: 'وُسم كصيانة مخطّطة',
    toastUnplanned: 'أُعيد إلى غير المخطّط',
    alertBanner: 'التنبيهات المطلقة على هذه الخدمة موجودة في طابور التنبيهات. رشّح بحالة «أي حالة» لترى المغلقة منها.',
    drawerTitle: ({ name, date }) => `${name} — ${date}`,
  },

  reports: {
    lead: ({ month, year }) => `المراجعة الشهرية للبنية التقنية عن ${month} ${year}. توليد مراجعة يجمّد الأرقام الحالية لتقارنها بها لاحقاً؛ وملف CSV هو ما ترفقه بدعوة الاجتماع.`,
    generate: 'توليد المراجعة الشهرية',
    tileRunRate: 'معدل الإنفاق',
    tileVs: ({ month }) => `مقابل ${month}`,
    tileUptime: 'التوافر',
    tileUptimeSub: ({ n }) => `${n} خدمات`,
    tileSaving: 'التوفير المتاح',
    tileSavingSub: ({ n }) => `${n} نتيجة`,
    notesTitle: ({ month, year }) => `ملاحظات المراجعة — ${month} ${year}`,
    noteSpend: 'الإنفاق',
    noteSpendText: ({ run, diff, dir, prev, mtd, day, days, sar }) => `معدل الإنفاق ${run} شهرياً، وهو ${dir} ${prev} بمقدار ${diff}. ومنذ بداية الشهر ${mtd} في اليوم ${day} من ${days}. وحصة كيان جدة تعادل ${sar}.`,
    above: 'فوق',
    below: 'تحت',
    noteEstate: 'البنية',
    onpremWord: 'محلي',
    noteEstateText: ({ n, split, untagged }) => `${n} مورداً: ${split}. و${untagged} منها ينقصها الوسوم المطلوبة فتقع في الإنفاق غير الموزّع.`,
    noteWaste: 'الهدر',
    noteWasteText: ({ n, money, planned }) => `${n} نتيجة بقيمة ${money} شهرياً. و${planned} منها ضمن خطة التنظيف.`,
    noteReliability: 'الموثوقية',
    noteReliabilityText: ({ pct, below }) => `توافر الأسطول ${pct} خلال 30 يوماً. و${below} من الخدمات دون الهدف.`,
    noteAlerts: 'التنبيهات',
    noteAlertsText: ({ open, acked, resolved }) => `${open} مفتوحة، و${acked} مستلَمة، و${resolved} أُغلقت في هذه الدورة.`,
    noteAccess: 'الوصول',
    noteAccessText: ({ noMfa, stale, keys }) => `${noMfa} من الحسابات ذات الصلاحيات الموسّعة بلا MFA، و${stale} حساباً راكداً، و${keys} من مفاتيح الوصول تجاوزت السنة.`,
    chartTitle: 'الإنفاق، آخر سبعة أشهر',
    downloads: 'التنزيلات',
    dlReview: 'المراجعة الشهرية كاملة',
    dlReviewSub: 'صف واحد لكل قسم مع الأرقام الرئيسية',
    dlInventory: 'جرد الموارد',
    dlRows: ({ n }) => `${n} صفاً`,
    dlCost: 'التكلفة حسب الخدمة والشهر',
    dlMonths: ({ n }) => `${n} أشهر`,
    dlWaste: 'الخمول والهدر',
    dlFindings: ({ n }) => `${n} نتيجة`,
    dlAccess: 'مراجعة الوصول',
    dlAccounts: ({ n }) => `${n} حساباً`,
    dlUptime: 'التوافر، 30 يوماً',
    dlServices: ({ n }) => `${n} خدمات`,
    generated: ({ id }) => `وُلّدت المراجعة ${id}`,
    listTitle: 'المراجعات المولَّدة',
    emptyTitle: 'لا مراجعات بعد',
    emptyBody: 'ولّد واحدة لتجميد أرقام هذا الشهر. المراجعات المحفوظة تبقى بعد إعادة التحميل.',
    thReview: 'المراجعة',
    thMonth: 'الشهر',
    thSpend: 'الإنفاق',
    thWaste: 'الهدر',
    thUptime: 'التوافر',
    thOpen: 'تنبيهات مفتوحة',
    thCreated: 'أُنشئت',
    downloadLabel: ({ id }) => `تنزيل ${id}`,
    deleteLabel: ({ id }) => `حذف ${id}`,
    deleteBody: ({ id }) => `حذف المراجعة ${id}؟`,
    deleteTitle: 'حذف المراجعة',
    deleteOk: 'حذف',
    deleted: 'حُذفت المراجعة',
    downloaded: 'نُزّلت المراجعة',
    /* CSV keeps its English column names: the file is opened in a
       spreadsheet and handed on, and the header row is the schema. */
    csvRows: EN.reports.csvRows,
  },

  /* ---------- the sample estate itself ----------
     Only the Arabic side carries these. In English the app reads the
     seeded text straight off the record, so English is byte for byte
     what it has always been. Metric names, hostnames, region codes,
     instance types and runbook ids stay in Latin: they are what an
     engineer types into a console. */
  data: {
    alerts: {
      'AL-2400': {
        title: 'FreeStorageSpace دون 8% على nl-prod-orders-pg',
        detail: 'المتاح 11.4 GB من أصل 200 GB. تضخّم احتفاظ WAL بعد توقّف فتحة النسخ على نسخة التقارير عند 02:41 أمس.',
        runbook: 'الدليل DB-04: احذف فتحة النسخ المتوقفة، ثم وسّع التخزين بمقدار 100 GB.',
      },
      'AL-2407': {
        title: 'عقدة خارج الجاهزية: ip-10-42-6-118 في eks-prod-ng-general',
        detail: 'توقّف kubelet عن الإبلاغ ست دقائق. أُخرجت إحدى عشرة حاوية وأُعيدت جدولتها على مجموعة عقد spot.',
        runbook: 'الدليل K8S-02: اعزل العقدة وفرّغها ثم استبدلها من مجموعة التوسّع.',
      },
      'AL-2414': {
        title: 'CPUUtilization فوق 90% لخمس عشرة دقيقة على nl-prod-api-03',
        detail: 'ثبات عند 91% منذ بدء تصريف تراكم الطابور. وسمت مجموعة الهدف المثيل غير سليم مرتين.',
        runbook: 'الدليل APP-01: وسّع مجموعة التوسّع بمثيل واحد وراجع سجل الاستعلامات البطيئة.',
      },
      'AL-2421': {
        title: 'فشل مهمة النسخ الاحتياطي: koc-veeam-repo (خادم ملفات كوتشي)',
        detail: 'فشلت المهمة «KOC-Fileserver-Daily» عند 04:20 بانتهاء مهلة المستودع. آخر نقطة استعادة سليمة عمرها 26 ساعة.',
        runbook: 'الدليل BK-02: أعد تشغيل المهمة، ثم افحص زمن استجابة المستودع على koc-san-lun01.',
      },
      'AL-2428': {
        title: 'TargetResponseTime p95 فوق ثانيتين على alb-prod-public',
        detail: 'بقي p95 عند 2.4 ثانية اثنتي عشرة دقيقة أثناء دفعة الطلبات الصباحية. لم تُسجّل أخطاء 5xx.',
        runbook: 'الدليل APP-03: تأكّد من حجم تجمّع الاتصالات على عمّال الطلبات.',
      },
      'AL-2435': {
        title: 'الشهادة تنتهي خلال 12 يوماً: ‎*.northline.co.in',
        detail: 'شهادة الحرف البديل على موازن الحمل العام تُجدَّد يدوياً لأن سجل التحقق عبر DNS أُزيل.',
        runbook: 'الدليل SEC-05: أعد سجل CNAME للتحقق ثم أصدر الشهادة من جديد.',
      },
      'AL-2442': {
        title: 'استخدام القرص 92% على jed-fac-app-vm01 (‎/var)',
        detail: 'توقّف تدوير سجلات التطبيق بعد أن أعادت ترقية الحزمة في 14 يوليو ضبط logrotate.conf.',
        runbook: 'الدليل OS-01: دوّر السجلات واضغطها، ثم أعد ملف logrotate الإضافي.',
      },
      'AL-2449': {
        title: 'DTU فوق 80% لعشرين دقيقة على kcf-prod-sql',
        detail: 'تداخلت مهمة تسوية المخزون مع إعادة بناء كتالوج المتجر.',
        runbook: 'الدليل DB-07: باعد بين المهمتين ثلاثين دقيقة.',
      },
      'AL-2456': {
        title: 'أُنشئ مفتاح وصول IAM جديد لـ svc-deploy',
        detail: 'أنشأ دور خط النشر المفتاح ‎AKIA…7QF2 أثناء الإصدار. المفتاح السابق ما زال نشطاً.',
        runbook: 'الدليل SEC-02: عطّل المفتاح المستبدَل بعد أول نشر ناجح.',
      },
      'AL-2463': {
        title: 'نفق VPN معطّل: jed-dc1 إلى me-central-1',
        detail: 'تذبذب النفق أربع مرات ليلاً قبل أن يستقر. عدم تطابق في إعادة مفاتيح المرحلة الثانية مع FortiGate.',
        runbook: 'الدليل NET-04: وحّد عمر المرحلة الثانية على الطرفين.',
      },
      'AL-2470': {
        title: 'وحدة EBS غير مرتبطة منذ أكثر من 30 يوماً: vol-07d9b104',
        detail: 'وحدة gp2 سعتها 1 TB غير مرتبطة منذ 38 يوماً وما زالت تُفوتر بالسعر الكامل.',
        runbook: 'الدليل FIN-01: خذ نسخة ثم احذفها، أو ضع عليها وسم تاريخ إبقاء.',
      },
      'AL-2477': {
        title: 'انقطاع الوصلة بين الموقعين: وصلة koc-dc1',
        detail: 'سقطت وصلة الألياف الأساسية 22 دقيقة. تحوّلت الحركة إلى دائرة النطاق العريض الاحتياطية.',
        runbook: 'الدليل NET-01: افتح تذكرة مع مزوّد الدائرة، وأبقِ التحويل قائماً حتى التأكيد.',
      },
      'AL-2484': {
        title: 'فحص صورة ECR: ثلاث ثغرات CVE مرتفعة في orders-api:2026.07.3',
        detail: 'ثلاث نتائج بخطورة مرتفعة في الصورة الأساسية، وكلها مُصلحة في إصدار الترقيع 3.19.2.',
        runbook: 'الدليل SEC-08: أعد البناء على الصورة المرقّعة ثم انشر.',
      },
      'AL-2491': {
        title: 'تغطية المثيلات المحجوزة هبطت إلى 61%',
        detail: 'انتهت خطتا توفير حوسبة لمدة سنة في أول الشهر.',
        runbook: 'الدليل FIN-03: أعد الشراء وفق الاستخدام المستقر الحالي.',
      },
    },
    waste: {
      'eks-dev-ng-general': {
        why: 'مجموعة عقد التطوير تعمل 24/7 مع أنه لا حِمل مجدولاً عليها خارج 09:00–19:00 بتوقيت الهند، خمسة أيام في الأسبوع',
        action: 'صفّر عدد عقد المجموعة وفق جدول زمني',
      },
      'nl-analytics-pg': {
        why: 'متوسط المعالج 3.1% ولم يُسجَّل أي اتصال في 21 يوماً من آخر 30 — انتقل الاستخراج الليلي إلى المستودع في يونيو',
        action: 'خذ نسخة ثم احذفها',
      },
      'alb-legacy-portal': {
        why: 'صفر طلبات منذ 41 يوماً — نُقلت بوابة المورّدين القديمة إلى المتجر الجديد في 12 يونيو',
        action: 'احذف موازن الحمل ومجموعة الأهداف التابعة له',
      },
      'nat-dev-az1': {
        why: 'مرّرت شبكات التطوير الفرعية 3.1 GB عبر هذه البوابة طوال الشهر — والرسم الساعي يشكّل 94% من الفاتورة',
        action: 'استبدلها بنقطة نهاية VPC أو ببوابة NAT مشتركة',
      },
      'nl-logs-archive': {
        why: 'لا طلبات GET منذ 118 يوماً وكل كائن أقدم من 90 يوماً، ومع ذلك ما زالت السلة على فئة Standard',
        action: 'أضف قاعدة دورة حياة إلى Glacier Instant Retrieval',
      },
      'vol-0f31c8a7': {
        why: 'فُصلت عن nl-dev-build-04 حين أُنهي ذلك المثيل قبل 63 يوماً ولم تُنظَّف بعدها',
        action: 'خذ نسخة، ثم احذف الوحدة',
      },
      'vol-07d9b104': {
        why: 'غير مرتبطة منذ 38 يوماً. كانت وحدة بيانات قاعدة الطلبات القديمة، أُبقيت «تحسّباً» بعد الترحيل إلى r6g',
        action: 'أبقِ النسخة واحذف الوحدة',
      },
      'eipalloc-04b2e7': {
        why: 'غير مقترن بأي مثيل أو واجهة منذ 74 يوماً — عنوان IPv4 العام الخامل يُفوتر بالساعة',
        action: 'حرّر العنوان',
      },
      'eipalloc-0c81f9': {
        why: 'غير مقترن بأي شيء منذ 51 يوماً',
        action: 'حرّر العنوان',
      },
      'nl-snapshots-legacy': {
        why: '318 نسخة يدوية بلا وسم احتفاظ، أقدمها من 2024. وأحد عشر منها فقط مرتبطة بصورة AMI',
        action: 'طبّق سياسة احتفاظ 35 يوماً عبر Data Lifecycle Manager',
      },
      'cw-logs-prod': {
        why: 'تسع عشرة مجموعة سجلات ضُبط احتفاظها على «بلا انتهاء»، ومنها مجموعتا تنقيح تُركتا بعد إصدار يونيو',
        action: 'اضبط احتفاظ 30 يوماً على مجموعتَي التنقيح',
      },
      'nl-stg-api-01': {
        why: 'بيئة الاختبار تعمل على مدار الساعة لكنها لا ترى حركة إلا في ساعات الدوام',
        action: 'اربطها بجدول التشغيل والإيقاف حسب ساعات المكتب',
      },
      'nl-stg-worker-01': {
        why: 'الصورة نفسها كما في nl-stg-api-01 — خمول في الليالي وعطلات الأسبوع',
        action: 'اربطها بجدول التشغيل والإيقاف حسب ساعات المكتب',
      },
      'nl-dev-sandbox-01': {
        why: 'بلغ المعالج ذروته عند 4% خلال 30 يوماً. رُفع المثيل لمهمة pandas لمرة واحدة في مايو ولم يُوقَف',
        action: 'أوقف المثيل، وأبقِ وحدة الجذر ثلاثين يوماً',
      },
      'aks-retail-stg': {
        why: 'عنقود الاختبار يعمل 720 ساعة في الشهر ويُستخدم نحو 45 ساعة منها',
        action: 'أوقف مجموعة العقد خارج 09:00–19:00 بتوقيت الهند',
      },
      'kcf-stg-sql': {
        why: 'متوسط استهلاك DTU هو 6% والذروة 14% — طبقة S0 تكفيه',
        action: 'انزل إلى طبقة الخدمة S0',
      },
      kcfstgdiag: {
        why: 'حاوية تشخيص إقلاع لأجهزة افتراضية حُذفت في مارس. ولا قراءات منذ ذلك الحين',
        action: 'احذف حساب التخزين',
      },
      'kcf-dev-vm05': {
        why: 'أُوقف من داخل نظام الضيف لا عبر إلغاء التخصيص — وAzure ما زالت تفوتر الحوسبة',
        action: 'ألغِ تخصيص الجهاز من البوابة أو من سطر الأوامر',
      },
      'koc-esx-04': {
        why: 'المضيف عند 17% من المعالج و24% من الذاكرة. والأجهزة التسعة عليه تتّسع داخل هامش koc-esx-03',
        action: 'انقل الضيوف بـ vMotion ثم أطفئ المضيف',
      },
      'koc-print-srv': {
        why: 'لا مهام طباعة منذ 64 يوماً — انتقل مكتب كوتشي إلى طابور follow-me على خادم جدة',
        action: 'أخرجه من الخدمة بعد مهلة إشعار أسبوعين',
      },
    },
  },

  /* ---------- Stackview Insight ----------
     المساعد يقرأ ويكتب بالإنجليزية: أنماط النوايا ورقائق الاقتراحات وسطور
     `ask` هي الجمل التي يكتبها القارئ له، فتبقى لاتينية في الجانبين. المترجم
     هنا هو كل ما تقوله اللوحة من عندها. */
  agent: {
    tag: 'وكيل تجريبي · يقرأ مساحة العمل هذه وحدها',
    greeting: ({ resources, alerts, users }) => `أقرأ البنية المعروضة أمامك — ${resources} مورداً و${alerts} تنبيهاً و${users} حساباً — وأجيب بالأرقام الظاهرة على الشاشة الآن.\n\nوأستطيع تنفيذ العمل لا وصفه فحسب: استلام التنبيهات، وبناء خطة التنظيف، وإيقاف مورد، ونقل مالك، وإصلاح حساب، ووسم ما هو غير مخصّص. أعرض عليك بالضبط ما سألمسه ثم أنتظر ضغطتك.\n\nأسئلتي تُكتب بالإنجليزية: اسأل **"what can you do?"**، أو جرّب واحدة من هذه، أو اكتب سؤالك بأسلوبك.`,
    note: 'وكيل تجريبي — كل إجابة تُركَّب محلياً من البنية التجريبية داخل هذا التطبيق. لا اتصال بالشبكة ولا نموذج.',
    fallbacks: [
      'I only answer from this workspace. Ask me what is idle, where the biggest cost jump came from, which admins have no MFA, or tell me to acknowledge everything critical from last night.',
      'That one is outside the demo data. I can pull spend by environment or team, the projected month end, the alert queue, uptime against SLO, or the access review — and I can change any of it on your say so.',
      'I could not match that to anything in the estate. Try "what is safe to switch off", "tag every untagged resource with its owner", or "which accounts are stale".',
      'No match in the current data. Ask "what can you do?" for the six things I can change, or ask me anything about cost, waste, alerts, uptime, access and inventory.',
    ],
    ui: {
      openLabel: ({ name }) => `فتح ${name}`,
      fabTitle: ({ name }) => `${name} — اسأل عن مساحة العمل هذه`,
      clear: 'مسح المحادثة',
      close: 'إغلاق',
      placeholder: 'اسأل شيئاً…',
      send: 'إرسال',
      you: 'أنت',
      working: 'جارٍ العمل…',
      done: 'تم.',
      answerError: 'اصطدم هذا السؤال بحدّ من حدود البيانات التجريبية. جرّب أحد الاقتراحات.',
      actionError: 'تعذّر تطبيق ذلك — قد يكون السجل تغيّر منذ أن قرأته.',
      applied: 'طُبّق التغيير في هذا المتصفح',
      searched: 'بحثت في فهرس مساحة العمل',
      seconds: ({ s }) => `${s}s`,
    },
    /* الأمور الستة التي يستطيع تغييرها، تظهر في لوحة «عن هذا العرض» وفي
       إجابة المساعد نفسه على "what can you do?" */
    actions: {
      alerts: {
        title: 'العمل على طابور التنبيهات',
        does: 'يسمّي التنبيهات الحرجة التي فُتحت في نافذة الليل ويعدّها، ثم يستلمها عند التأكيد باسم Aravind Menon، ويكتب سطراً في الخط الزمني لكل تنبيه، ويعرض الطابور قبل وبعد. وجملة "Mute the certificate alert for 24 hours" تفعل ذلك لتنبيه واحد.',
        screen: 'التنبيهات',
      },
      plan: {
        title: 'بناء خطة التنظيف',
        does: 'يعرض الاكتشافات الثلاثة التي سيلتقطها مع توفير كل منها شهرياً، ثم يضيفها ويبيّن انتقال الخطة من رقم إلى رقم، مع المبلغ السنوي.',
        screen: 'التكلفة ← الخمول والهدر',
      },
      stop: {
        title: 'إيقاف مورد',
        does: 'يقرأ المورد وبيئته ومالكه وسحبه الشهري، ثم يوقفه. وكل ما هو في الإنتاج يحتاج تأكيداً على زر يقول ذلك صراحة، ويسمّي الخدمة التي يسندها المورد قبل أن تضغط.',
        screen: 'الموارد',
      },
      reassign: {
        title: 'نقل الملكية',
        does: 'ينقل المالك ووسم Owner، ويبيّن حجم الإنفاق الشهري الذي انتقل من شخص إلى آخر.',
        screen: 'الموارد · الوصول',
      },
      account: {
        title: 'إصلاح حساب',
        does: 'يشغّل العامل الثاني ويعرض تغطية MFA قبل وبعد. أما "Start offboarding for Ashraf Kunhi" فتفتح قائمة الخطوات السبع بدلاً من ذلك.',
        screen: 'الوصول',
      },
      tag: {
        title: 'وسم ما هو غير مخصّص',
        does: 'يطبّق Owner وCostCentre وManagedBy على الموارد التي لا وسوم لها، ويبيّن حجم الإنفاق الشهري الذي خرج من خانة غير المخصّص.',
        screen: 'الموارد · التكلفة ← حسب الفريق',
      },
    },
  },
};

export const STRINGS = { en: EN, ar: AR };
